
{{- with .Values.n3iwf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coran-n3iwf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "coran-n3iwf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coran-n3iwf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "coran-n3iwf.n3iwfAnnotations" $ | nindent 8 }}
        k8s.v1.cni.cncf.io/networks: '[
        {{- if not $.Values.global.amf.service.ngap.enabled }}
            { "name": "{{ $.Values.global.n2network.name }}-{{ .name }}",
              "interface": "n2",
              "ips": [ "{{ .n2if.ipAddress }}/{{ $.Values.global.n2network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n2network.gatewayIP }}" ]
            },
        {{- end }}
            { "name": "{{ $.Values.global.n3network.name }}-{{ .name }}",
              "interface": "n3",
              "ips": [ "{{ .n3if.ipAddress }}/{{ $.Values.global.n3network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.n3network.gatewayIP }}" ]
            },

            { "name": "{{ .ike.name }}-{{ .name }}",
              "interface": "ike",
              "ips": [ "{{ .ike.ipAddress }}/{{ .ike.cidr }}" ],
              "gateway": [ "{{ .ike.gatewayIP }}" ]
            }            
            ]'
        checksum/config: {{ include (print $.Template.BasePath "/n3iwf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "coran-n3iwf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .name }}
        image: {{ $.Values.global.n3iwf.image.name }}
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        command: ["sh", "-c", "../config/n3iwf-ipsec.sh && ./n3iwf -c ../config/n3iwfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: n3iwfcfg.yaml
                path: n3iwfcfg.yaml
              - key: n3iwf-ipsec.sh
                path: n3iwf-ipsec.sh
                mode: 0777
{{- end }}