/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

import (
	"context"
	"errors"
	"net/http"
)

// SubscriptionsCollectionApiService is a service that implements the logic for the SubscriptionsCollectionApiServicer
// This service should implement the business logic for every endpoint for the SubscriptionsCollectionApi API.
// Include any external packages or services that will be required by this service.
type SubscriptionsCollectionApiService struct {
}

// NewSubscriptionsCollectionApiService creates a default api service
func NewSubscriptionsCollectionApiService() SubscriptionsCollectionApiServicer {
	return &SubscriptionsCollectionApiService{}
}

// CreateNWDAFMLModelProvisionSubcription - Create a new Individual NWDAF ML Model Provision Subscription resource.
func (s *SubscriptionsCollectionApiService) CreateNWDAFMLModelProvisionSubcription(ctx context.Context, nwdafMlModelProvSubsc NwdafMlModelProvSubsc) (ImplResponse, error) {
	// TODO - update CreateNWDAFMLModelProvisionSubcription with the required logic for this service method.
	// Add api_subscriptions_collection_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, NwdafMlModelProvSubsc{}) or use other options such as http.Ok ...
	//return Response(201, NwdafMlModelProvSubsc{}), nil

	//TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(400, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(401, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(403, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(404, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(411, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(413, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(415, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(429, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(500, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(503, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateNWDAFMLModelProvisionSubcription method not implemented")
}
