/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type MatchingDirectionAnyOf string

// List of MatchingDirectionAnyOf
const (
	MATCHINGDIRECTIONANYOF_ASCENDING  MatchingDirectionAnyOf = "ASCENDING"
	MATCHINGDIRECTIONANYOF_DESCENDING MatchingDirectionAnyOf = "DESCENDING"
	MATCHINGDIRECTIONANYOF_CROSSED    MatchingDirectionAnyOf = "CROSSED"
)

// AssertMatchingDirectionAnyOfRequired checks if the required fields are not zero-ed
func AssertMatchingDirectionAnyOfRequired(obj MatchingDirectionAnyOf) error {
	return nil
}

// AssertRecurseMatchingDirectionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MatchingDirectionAnyOf (e.g. [][]MatchingDirectionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMatchingDirectionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMatchingDirectionAnyOf, ok := obj.(MatchingDirectionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMatchingDirectionAnyOfRequired(aMatchingDirectionAnyOf)
	})
}
