/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type DispersionTypeOneOf string

// List of DispersionTypeOneOf
const (
	DISPERSIONTYPEONEOF_DVDA         DispersionTypeOneOf = "DVDA"
	DISPERSIONTYPEONEOF_TDA          DispersionTypeOneOf = "TDA"
	DISPERSIONTYPEONEOF_DVDA_AND_TDA DispersionTypeOneOf = "DVDA_AND_TDA"
)

// AssertDispersionTypeOneOfRequired checks if the required fields are not zero-ed
func AssertDispersionTypeOneOfRequired(obj DispersionTypeOneOf) error {
	return nil
}

// AssertRecurseDispersionTypeOneOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DispersionTypeOneOf (e.g. [][]DispersionTypeOneOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDispersionTypeOneOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDispersionTypeOneOf, ok := obj.(DispersionTypeOneOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDispersionTypeOneOfRequired(aDispersionTypeOneOf)
	})
}
