/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type DispersionClassOneOf string

// List of DispersionClassOneOf
const (
	DISPERSIONCLASSONEOF_FIXED     DispersionClassOneOf = "FIXED"
	DISPERSIONCLASSONEOF_CAMPER    DispersionClassOneOf = "CAMPER"
	DISPERSIONCLASSONEOF_TRAVELLER DispersionClassOneOf = "TRAVELLER"
	DISPERSIONCLASSONEOF_TOP_HEAVY DispersionClassOneOf = "TOP_HEAVY"
)

// AssertDispersionClassOneOfRequired checks if the required fields are not zero-ed
func AssertDispersionClassOneOfRequired(obj DispersionClassOneOf) error {
	return nil
}

// AssertRecurseDispersionClassOneOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DispersionClassOneOf (e.g. [][]DispersionClassOneOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDispersionClassOneOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDispersionClassOneOf, ok := obj.(DispersionClassOneOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDispersionClassOneOfRequired(aDispersionClassOneOf)
	})
}
