/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// Ipv6Addr - String identifying an IPv6 address formatted according to clause 4 of RFC5952. The mixed IPv4 IPv6 notation according to clause 5 of RFC5952 shall not be used
type Ipv6Addr struct {
}

// AssertIpv6AddrRequired checks if the required fields are not zero-ed
func AssertIpv6AddrRequired(obj Ipv6Addr) error {
	return nil
}

// AssertRecurseIpv6AddrRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Ipv6Addr (e.g. [][]Ipv6Addr), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIpv6AddrRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIpv6Addr, ok := obj.(Ipv6Addr)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIpv6AddrRequired(aIpv6Addr)
	})
}
