/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type EllipsoidArcAllOf struct {
	Point GeographicalCoordinates `json:"point"`

	// Indicates value of the inner radius.
	InnerRadius int32 `json:"innerRadius"`

	// Indicates value of uncertainty.
	UncertaintyRadius float32 `json:"uncertaintyRadius"`

	// Indicates value of angle.
	OffsetAngle int32 `json:"offsetAngle"`

	// Indicates value of angle.
	IncludedAngle int32 `json:"includedAngle"`

	// Indicates value of confidence.
	Confidence int32 `json:"confidence"`
}

// AssertEllipsoidArcAllOfRequired checks if the required fields are not zero-ed
func AssertEllipsoidArcAllOfRequired(obj EllipsoidArcAllOf) error {
	elements := map[string]interface{}{
		"point":             obj.Point,
		"innerRadius":       obj.InnerRadius,
		"uncertaintyRadius": obj.UncertaintyRadius,
		"offsetAngle":       obj.OffsetAngle,
		"includedAngle":     obj.IncludedAngle,
		"confidence":        obj.Confidence,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertGeographicalCoordinatesRequired(obj.Point); err != nil {
		return err
	}
	return nil
}

// AssertRecurseEllipsoidArcAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EllipsoidArcAllOf (e.g. [][]EllipsoidArcAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEllipsoidArcAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEllipsoidArcAllOf, ok := obj.(EllipsoidArcAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEllipsoidArcAllOfRequired(aEllipsoidArcAllOf)
	})
}
