/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// FailureEventInfoForMlModel - Represents the event(s) that the subscription is not successful including the failure reason(s).
type FailureEventInfoForMlModel struct {
	Event NwdafEvent `json:"event"`

	FailureCode FailureCode `json:"failureCode"`
}

// AssertFailureEventInfoForMlModelRequired checks if the required fields are not zero-ed
func AssertFailureEventInfoForMlModelRequired(obj FailureEventInfoForMlModel) error {
	elements := map[string]interface{}{
		"event":       obj.Event,
		"failureCode": obj.FailureCode,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNwdafEventRequired(obj.Event); err != nil {
		return err
	}
	if err := AssertFailureCodeRequired(obj.FailureCode); err != nil {
		return err
	}
	return nil
}

// AssertRecurseFailureEventInfoForMlModelRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FailureEventInfoForMlModel (e.g. [][]FailureEventInfoForMlModel), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFailureEventInfoForMlModelRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFailureEventInfoForMlModel, ok := obj.(FailureEventInfoForMlModel)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFailureEventInfoForMlModelRequired(aFailureEventInfoForMlModel)
	})
}
