# Copyright 2019 Communication Service/Software Laboratory, National Chiao Tung University (free5gc.org)
#
# SPDX-License-Identifier: Apache-2.0

name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
