
{{- with .Values.gnb }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.projectName }}
    component: {{ .name }}
data:
  gnb-config.yaml: |

    {{- .configuration | nindent 4 }}
    
    linkIp: 0.0.0.0   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    # gNB's local IP address for N2 Interface (Usually same with local IP)
{{- if .amf.service.ngap.enabled }}
    ngapIp: 0.0.0.0   
{{- else }}
    ngapIp: {{ .n2if.ipAddress }} 
{{- end }}
    gtpIp: {{ .n3if.ipAddress }}    # gNB's local IP address for N3 Interface (Usually same with local IP)
    
    # List of AMF address information
    amfConfigs:
      - address: {{ .amf.n2if.ipAddress }}
        port: {{ .amf.n2if.port }}

{{- end }}
{{- end }}
