apiVersion: v1
kind: Service
metadata:
  name: {{ include "hexaupf.fullname" . }}
  labels:
    {{- include "hexaupf.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.deploymentType "statefulset" }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.extraPorts }}
    {{- include "helpers.common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "hexaupf.selectorLabels" . | nindent 4 }}
