/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

import (
	"time"
)

// WlanPerTsPerformanceInfo - WLAN performance information per Time Slot during the analytics target period.
type WlanPerTsPerformanceInfo struct {

	// string with format 'date-time' as defined in OpenAPI.
	TsStart time.Time `json:"tsStart"`

	// indicating a time in seconds.
	TsDuration int32 `json:"tsDuration"`

	Rssi int32 `json:"rssi,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Rtt int32 `json:"rtt,omitempty"`

	TrafficInfo TrafficInformation `json:"trafficInfo,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NumberOfUes int32 `json:"numberOfUes,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Confidence int32 `json:"confidence,omitempty"`
}

// AssertWlanPerTsPerformanceInfoRequired checks if the required fields are not zero-ed
func AssertWlanPerTsPerformanceInfoRequired(obj WlanPerTsPerformanceInfo) error {
	elements := map[string]interface{}{
		"tsStart":    obj.TsStart,
		"tsDuration": obj.TsDuration,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertTrafficInformationRequired(obj.TrafficInfo); err != nil {
		return err
	}
	return nil
}

// AssertRecurseWlanPerTsPerformanceInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WlanPerTsPerformanceInfo (e.g. [][]WlanPerTsPerformanceInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWlanPerTsPerformanceInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWlanPerTsPerformanceInfo, ok := obj.(WlanPerTsPerformanceInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWlanPerTsPerformanceInfoRequired(aWlanPerTsPerformanceInfo)
	})
}
