/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// RedTransExpOrderingCriterion - Possible values are   - TIME_SLOT_START: Indicates the order of time slot start.   - RED_TRANS_EXP: Indicates the order of Redundant Transmission Experience.
type RedTransExpOrderingCriterion struct {
}

// AssertRedTransExpOrderingCriterionRequired checks if the required fields are not zero-ed
func AssertRedTransExpOrderingCriterionRequired(obj RedTransExpOrderingCriterion) error {
	return nil
}

// AssertRecurseRedTransExpOrderingCriterionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RedTransExpOrderingCriterion (e.g. [][]RedTransExpOrderingCriterion), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRedTransExpOrderingCriterionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRedTransExpOrderingCriterion, ok := obj.(RedTransExpOrderingCriterion)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRedTransExpOrderingCriterionRequired(aRedTransExpOrderingCriterion)
	})
}
