/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// ConsumerNfInformation - Represents the analytics consumer NF Information.
type ConsumerNfInformation struct {

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	NfId string `json:"nfId,omitempty"`

	TaiList []Tai `json:"taiList,omitempty"`
}

// AssertConsumerNfInformationRequired checks if the required fields are not zero-ed
func AssertConsumerNfInformationRequired(obj ConsumerNfInformation) error {
	for _, el := range obj.TaiList {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseConsumerNfInformationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConsumerNfInformation (e.g. [][]ConsumerNfInformation), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConsumerNfInformationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConsumerNfInformation, ok := obj.(ConsumerNfInformation)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConsumerNfInformationRequired(aConsumerNfInformation)
	})
}
