/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// DispersionType - Possible values are   - DVDA: Data Volume Dispersion Analytics.   - TDA: Transactions Dispersion Analytics.   - DVDA_AND_TDA: Data Volume Dispersion Analytics and Transactions Dispersion Analytics.
type DispersionType struct {
}

// AssertDispersionTypeRequired checks if the required fields are not zero-ed
func AssertDispersionTypeRequired(obj DispersionType) error {
	return nil
}

// AssertRecurseDispersionTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DispersionType (e.g. [][]DispersionType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDispersionTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDispersionType, ok := obj.(DispersionType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDispersionTypeRequired(aDispersionType)
	})
}
