/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// WlanPerformanceReq - Represents other WLAN performance analytics requirements.
type WlanPerformanceReq struct {
	SsIds []string `json:"ssIds,omitempty"`

	BssIds []string `json:"bssIds,omitempty"`

	WlanOrderCriter WlanOrderingCriterion `json:"wlanOrderCriter,omitempty"`

	Order MatchingDirection `json:"order,omitempty"`
}

// AssertWlanPerformanceReqRequired checks if the required fields are not zero-ed
func AssertWlanPerformanceReqRequired(obj WlanPerformanceReq) error {
	if err := AssertWlanOrderingCriterionRequired(obj.WlanOrderCriter); err != nil {
		return err
	}
	if err := AssertMatchingDirectionRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertRecurseWlanPerformanceReqRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WlanPerformanceReq (e.g. [][]WlanPerformanceReq), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWlanPerformanceReqRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWlanPerformanceReq, ok := obj.(WlanPerformanceReq)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWlanPerformanceReqRequired(aWlanPerformanceReq)
	})
}
