/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// RoutingAreaId - Contains a Routing Area Identification as defined in 3GPP TS 23.003, clause 4.2.
type RoutingAreaId struct {
	PlmnId PlmnId `json:"plmnId"`

	// Location Area Code
	Lac string `json:"lac"`

	// Routing Area Code
	Rac string `json:"rac"`
}

// AssertRoutingAreaIdRequired checks if the required fields are not zero-ed
func AssertRoutingAreaIdRequired(obj RoutingAreaId) error {
	elements := map[string]interface{}{
		"plmnId": obj.PlmnId,
		"lac":    obj.Lac,
		"rac":    obj.Rac,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPlmnIdRequired(obj.PlmnId); err != nil {
		return err
	}
	return nil
}

// AssertRecurseRoutingAreaIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RoutingAreaId (e.g. [][]RoutingAreaId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRoutingAreaIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRoutingAreaId, ok := obj.(RoutingAreaId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRoutingAreaIdRequired(aRoutingAreaId)
	})
}
