/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// NfStatus - Contains the percentage of time spent on various NF states.
type NfStatus struct {

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	StatusRegistered int32 `json:"statusRegistered,omitempty"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	StatusUnregistered int32 `json:"statusUnregistered,omitempty"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	StatusUndiscoverable int32 `json:"statusUndiscoverable,omitempty"`
}

// AssertNfStatusRequired checks if the required fields are not zero-ed
func AssertNfStatusRequired(obj NfStatus) error {
	return nil
}

// AssertRecurseNfStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NfStatus (e.g. [][]NfStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNfStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNfStatus, ok := obj.(NfStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNfStatusRequired(aNfStatus)
	})
}
