/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NoProfileMatchReasonAnyOf string

// List of NoProfileMatchReasonAnyOf
const (
// REQUESTER_PLMN_NOT_ALLOWED        NoProfileMatchReasonAnyOf = "REQUESTER_PLMN_NOT_ALLOWED"
// TARGET_NF_SUSPENDED               NoProfileMatchReasonAnyOf = "TARGET_NF_SUSPENDED"
// TARGET_NF_UNDISCOVERABLE          NoProfileMatchReasonAnyOf = "TARGET_NF_UNDISCOVERABLE"
// QUERY_PARAMS_COMBINATION_NO_MATCH NoProfileMatchReasonAnyOf = "QUERY_PARAMS_COMBINATION_NO_MATCH"
// TARGET_NF_TYPE_NOT_SUPPORTED      NoProfileMatchReasonAnyOf = "TARGET_NF_TYPE_NOT_SUPPORTED"
// UNSPECIFIED                       NoProfileMatchReasonAnyOf = "UNSPECIFIED"
)
