/*
 *
 * AUSF Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cmd

import (
	"context"
	"os"
	"os/signal"

	"syscall"

	"github.com/coranlabs/CORAN_AUSF/Application_entity/logger"
	"github.com/coranlabs/CORAN_AUSF/Application_entity/pkg/factory"
	"github.com/coranlabs/CORAN_AUSF/Application_entity/pkg/service"

	//logger_util "github.com/coranlabs/CORAN_LIB_UTIL/logger"
	"github.com/coranlabs/CORAN_LIB_UTIL/version"
)

var AUSF *service.AusfApp

func Action() error {
	tlsKeyLogPath := ""

	logger.MainLog.Infoln("AUSF version: ", version.GetVersion())

	ctx, cancel := context.WithCancel(context.Background())
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)

	go func() {
		<-sigCh  // Wait for interrupt signal to gracefully shutdown
		cancel() // Notify each goroutine and wait them stopped
	}()

	cfg, err := factory.ReadConfig("./config/CORAN_AUSF.yaml")
	if err != nil {
		sigCh <- nil
		return err
	}
	factory.AusfConfig = cfg

	ausf, err := service.NewApp(ctx, cfg, tlsKeyLogPath)
	if err != nil {
		sigCh <- nil
		return err
	}
	AUSF = ausf

	ausf.Start()

	return nil
}

// func initLogFile(logNfPath []string) (string, error) {
// 	logTlsKeyPath := ""

// 	for _, path := range logNfPath {
// 		if err := logger_util.LogFileHook(logger.Log, path); err != nil {
// 			return "", err
// 		}

// 		if logTlsKeyPath != "" {
// 			continue
// 		}

// 		nfDir, _ := filepath.Split(path)
// 		tmpDir := filepath.Join(nfDir, "key")
// 		if err := os.MkdirAll(tmpDir, 0o775); err != nil {
// 			logger.InitLog.Errorf("Make directory %s failed: %+v", tmpDir, err)
// 			return "", err
// 		}
// 		_, name := filepath.Split(factory.AusfDefaultTLSKeyLogPath)
// 		logTlsKeyPath = filepath.Join(tmpDir, name)
// 	}

// 	return logTlsKeyPath, nil
// }
