#AMF
AMF_IP_ADDR=http://192.168.70.132:8080
AMF_HTTP_VERSION=2
AMF_SUBSCR_ROUTE=/namf-evts/v1
AMF_API_ROUTE=/test/amf
AMF_NOTIFY_CORRELATION_ID=string
AMF_NOTIFICATION_ID=1
AMF_NOTIFICATION_FORWARD_ROUTE=/sbi/notification/amf
# SMF
SMF_IP_ADDR=http://192.168.70.133:8080
SMF_HTTP_VERSION=2
SMF_SUBSCR_ROUTE=/nsmf_event-exposure/v1
SMF_API_ROUTE=/test/smf
SMF_NOTIFY_CORRELATION_ID=string
SMF_NOTIFICATION_ID=2
SMF_NOTIFICATION_FORWARD_ROUTE=/sbi/notification/smf
# Database
MONGODB_URI=mongodb://localhost:27017
MONGODB_DATABASE_NAME=testing
MONGODB_COLLECTION_NAME_AMF=amf
MONGODB_COLLECTION_NAME_SMF=smf
# Server
EVENT_NOTIFY_URI=http://192.168.70.1:8885
SERVER_ADDR=0.0.0.0:8885