# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cert-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Mi  # Ensure this is less than or equal to PV size
#   storageClassName: manual

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.global.persistentVolumeClaim.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.persistentVolumeClaim.size }}
  storageClassName: manual
