
{{- with .Values.pcf }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coran-pcf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "coran-pcf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coran-pcf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "coran-pcf.pcfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/pcf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "coran-pcf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      # initContainers:
      # - name: wait-nrf
      #   {{- with $.Values.initcontainers.curl }}
      #   image: {{ .registry }}/{{ .image }}:{{ .tag }}
      #   {{- end }}
      #   env:
      #   - name: DEPENDENCIES
      #     value: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
      #   command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']


      containers:
      - name: {{ .name }}
        image: {{ $.Values.global.chf.image.name }}
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .service.port }}
        command: ["./chf"] #["/bin/sh", "-c", "sleep 20000"]
          #args: ["-c", "../config/pcfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /root/cert
          name: cert-storage
        - mountPath: {{ .volume.mount }}
          name: {{ include "coran-pcf.fullname" $ }}-volume
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: cert-storage
        persistentVolumeClaim:
          claimName: {{ $.Values.global.persistentVolumeClaim.name }}
      - name: {{ include "coran-pcf.fullname" $ }}-volume
        projected:
          sources:
          - configMap:
              name: {{ include "coran-pcf.fullname" $ }}-configmap
{{- end }}
