/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type StatusAnyOf string

// List of StatusAnyOf
const (
	OPERATIVE     StatusAnyOf = "OPERATIVE"
	NON_OPERATIVE StatusAnyOf = "NON_OPERATIVE"
)
