/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

import (
	"context"
	"net/http"
)

// global variable to map subscription id and channel id.
// to update subscription, kill the previous go routine and set channel adress for the new one using the same subscription id.
// to remove subscription, kill the go routine using channel adress from the table.
var subscriptionTable = make(map[string]chan string)

// IndividualNWDAFEventSubscriptionTransferDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualNWDAFEventSubscriptionTransferDocumentApi
// The IndividualNWDAFEventSubscriptionTransferDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualNWDAFEventSubscriptionTransferDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualNWDAFEventSubscriptionTransferDocumentApiRouter interface {
	DeleteNWDAFEventSubscriptionTransfer(http.ResponseWriter, *http.Request)
	UpdateNWDAFEventSubscriptionTransfer(http.ResponseWriter, *http.Request)
}

// IndividualNWDAFEventsSubscriptionDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualNWDAFEventsSubscriptionDocumentApi
// The IndividualNWDAFEventsSubscriptionDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualNWDAFEventsSubscriptionDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualNWDAFEventsSubscriptionDocumentApiRouter interface {
	DeleteNWDAFEventsSubscription(http.ResponseWriter, *http.Request)
	UpdateNWDAFEventsSubscription(http.ResponseWriter, *http.Request)
}

// NWDAFEventSubscriptionTransfersCollectionApiRouter defines the required methods for binding the api requests to a responses for the NWDAFEventSubscriptionTransfersCollectionApi
// The NWDAFEventSubscriptionTransfersCollectionApiRouter implementation should parse necessary information from the http request,
// pass the data to a NWDAFEventSubscriptionTransfersCollectionApiServicer to perform the required actions, then write the service results to the http response.
type NWDAFEventSubscriptionTransfersCollectionApiRouter interface {
	CreateNWDAFEventSubscriptionTransfer(http.ResponseWriter, *http.Request)
}

// NWDAFEventsSubscriptionsCollectionApiRouter defines the required methods for binding the api requests to a responses for the NWDAFEventsSubscriptionsCollectionApi
// The NWDAFEventsSubscriptionsCollectionApiRouter implementation should parse necessary information from the http request,
// pass the data to a NWDAFEventsSubscriptionsCollectionApiServicer to perform the required actions, then write the service results to the http response.
type NWDAFEventsSubscriptionsCollectionApiRouter interface {
	CreateNWDAFEventsSubscription(http.ResponseWriter, *http.Request)
}

// IndividualNWDAFEventSubscriptionTransferDocumentApiServicer defines the api actions for the IndividualNWDAFEventSubscriptionTransferDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualNWDAFEventSubscriptionTransferDocumentApiServicer interface {
	DeleteNWDAFEventSubscriptionTransfer(context.Context, string) (ImplResponse, error)
	UpdateNWDAFEventSubscriptionTransfer(context.Context, string, AnalyticsSubscriptionsTransfer) (ImplResponse, error)
}

// IndividualNWDAFEventsSubscriptionDocumentApiServicer defines the api actions for the IndividualNWDAFEventsSubscriptionDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualNWDAFEventsSubscriptionDocumentApiServicer interface {
	DeleteNWDAFEventsSubscription(context.Context, string) (ImplResponse, error)
	UpdateNWDAFEventsSubscription(context.Context, string, NnwdafEventsSubscription) (ImplResponse, error)
}

// NWDAFEventSubscriptionTransfersCollectionApiServicer defines the api actions for the NWDAFEventSubscriptionTransfersCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NWDAFEventSubscriptionTransfersCollectionApiServicer interface {
	CreateNWDAFEventSubscriptionTransfer(context.Context, AnalyticsSubscriptionsTransfer) (ImplResponse, error)
}

// NWDAFEventsSubscriptionsCollectionApiServicer defines the api actions for the NWDAFEventsSubscriptionsCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type NWDAFEventsSubscriptionsCollectionApiServicer interface {
	CreateNWDAFEventsSubscription(context.Context, NnwdafEventsSubscription, string) (ImplResponse, error)
}
