/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// HfcNodeId - REpresents the HFC Node Identifer received over NGAP.
type HfcNodeId struct {

	// This IE represents the identifier of the HFC node Id as specified in CableLabs WR-TR-5WWC-ARCH. It is provisioned by the wireline operator as part of wireline operations and may contain up to six characters.
	HfcNId string `json:"hfcNId"`
}

// AssertHfcNodeIdRequired checks if the required fields are not zero-ed
func AssertHfcNodeIdRequired(obj HfcNodeId) error {
	elements := map[string]interface{}{
		"hfcNId": obj.HfcNId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseHfcNodeIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HfcNodeId (e.g. [][]HfcNodeId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHfcNodeIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHfcNodeId, ok := obj.(HfcNodeId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHfcNodeIdRequired(aHfcNodeId)
	})
}
