/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// TargetUeInformation1 - Identifies the target UE information.
type TargetUeInformation1 struct {
	AnyUe bool `json:"anyUe,omitempty"`

	Supis []string `json:"supis,omitempty"`

	Gpsis []string `json:"gpsis,omitempty"`

	IntGroupIds []string `json:"intGroupIds,omitempty"`
}

// AssertTargetUeInformation1Required checks if the required fields are not zero-ed
func AssertTargetUeInformation1Required(obj TargetUeInformation1) error {
	return nil
}

// AssertRecurseTargetUeInformation1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TargetUeInformation1 (e.g. [][]TargetUeInformation1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTargetUeInformation1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTargetUeInformation1, ok := obj.(TargetUeInformation1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTargetUeInformation1Required(aTargetUeInformation1)
	})
}
