/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// NetworkPerfInfo1 - Represents the network performance information.
type NetworkPerfInfo1 struct {
	NetworkArea NetworkAreaInfo `json:"networkArea"`

	NwPerfType NetworkPerfType `json:"nwPerfType"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	RelativeRatio int32 `json:"relativeRatio,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AbsoluteNum int32 `json:"absoluteNum,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Confidence int32 `json:"confidence,omitempty"`
}

// AssertNetworkPerfInfo1Required checks if the required fields are not zero-ed
func AssertNetworkPerfInfo1Required(obj NetworkPerfInfo1) error {
	elements := map[string]interface{}{
		"networkArea": obj.NetworkArea,
		"nwPerfType":  obj.NwPerfType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkAreaInfoRequired(obj.NetworkArea); err != nil {
		return err
	}
	if err := AssertNetworkPerfTypeRequired(obj.NwPerfType); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNetworkPerfInfo1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NetworkPerfInfo1 (e.g. [][]NetworkPerfInfo1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNetworkPerfInfo1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNetworkPerfInfo1, ok := obj.(NetworkPerfInfo1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNetworkPerfInfo1Required(aNetworkPerfInfo1)
	})
}
