/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// TransferRequestType - Possible values are - PREPARE: Indicates that the request is for analytics subscription transfer preparation. - TRANSFER: Indicates that the request is for analytics subscription transfer execution.
type TransferRequestType struct {
}

// AssertTransferRequestTypeRequired checks if the required fields are not zero-ed
func AssertTransferRequestTypeRequired(obj TransferRequestType) error {
	return nil
}

// AssertRecurseTransferRequestTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TransferRequestType (e.g. [][]TransferRequestType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTransferRequestTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTransferRequestType, ok := obj.(TransferRequestType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTransferRequestTypeRequired(aTransferRequestType)
	})
}
