/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

type NotificationMethodAnyOf string

// List of NotificationMethodAnyOf
const (
	NOTIFICATIONMETHODANYOF_PERIODIC  NotificationMethodAnyOf = "PERIODIC"
	NOTIFICATIONMETHODANYOF_THRESHOLD NotificationMethodAnyOf = "THRESHOLD"
)

// AssertNotificationMethodAnyOfRequired checks if the required fields are not zero-ed
func AssertNotificationMethodAnyOfRequired(obj NotificationMethodAnyOf) error {
	return nil
}

// AssertRecurseNotificationMethodAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotificationMethodAnyOf (e.g. [][]NotificationMethodAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotificationMethodAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotificationMethodAnyOf, ok := obj.(NotificationMethodAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotificationMethodAnyOfRequired(aNotificationMethodAnyOf)
	})
}
