/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

type QosResourceTypeAnyOf string

// List of QosResourceTypeAnyOf
const (
	QOSRESOURCETYPEANYOF_NON_GBR          QosResourceTypeAnyOf = "NON_GBR"
	QOSRESOURCETYPEANYOF_NON_CRITICAL_GBR QosResourceTypeAnyOf = "NON_CRITICAL_GBR"
	QOSRESOURCETYPEANYOF_CRITICAL_GBR     QosResourceTypeAnyOf = "CRITICAL_GBR"
)

// AssertQosResourceTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertQosResourceTypeAnyOfRequired(obj QosResourceTypeAnyOf) error {
	return nil
}

// AssertRecurseQosResourceTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of QosResourceTypeAnyOf (e.g. [][]QosResourceTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseQosResourceTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aQosResourceTypeAnyOf, ok := obj.(QosResourceTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertQosResourceTypeAnyOfRequired(aQosResourceTypeAnyOf)
	})
}
