/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// SvcExperience - Contains a mean opinion score with the customized range.
type SvcExperience struct {

	// string with format 'float' as defined in OpenAPI.
	Mos float32 `json:"mos,omitempty"`

	// string with format 'float' as defined in OpenAPI.
	UpperRange float32 `json:"upperRange,omitempty"`

	// string with format 'float' as defined in OpenAPI.
	LowerRange float32 `json:"lowerRange,omitempty"`
}

// AssertSvcExperienceRequired checks if the required fields are not zero-ed
func AssertSvcExperienceRequired(obj SvcExperience) error {
	return nil
}

// AssertRecurseSvcExperienceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SvcExperience (e.g. [][]SvcExperience), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSvcExperienceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSvcExperience, ok := obj.(SvcExperience)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSvcExperienceRequired(aSvcExperience)
	})
}
