/*
Nsmf_EventExposure

Session Management Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package smfclient

import (
	"encoding/json"
	"time"
	"strconv"
)

// EventNotification Represents a notification related to a single event that occurred.
type EventNotification struct {
	Event SmfEventAnyOf `json:"event"`
	// string with format 'date-time' as defined in OpenAPI.
	TimeStamp time.Time // `json:"timeStamp"` - custom UnmarshalJSON
	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2 of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2 of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall only contain characters allowed according to the \"lower-with-hyphen\" naming convention defined in 3GPP TS 29.501. 
	Supi *string `json:"supi,omitempty"`
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-<extid>, where <extid>  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	Gpsi *string `json:"gpsi,omitempty"`
	UeIpAddr *IpAddr `json:"ueIpAddr,omitempty"`
	// Transaction Information.
	TransacInfos []TransactionInfo `json:"transacInfos,omitempty"`
	// DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.
	SourceDnai *string `json:"sourceDnai,omitempty"`
	// DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.
	TargetDnai *string `json:"targetDnai,omitempty"`
	DnaiChgType *DnaiChangeType `json:"dnaiChgType,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	SourceUeIpv4Addr *string `json:"sourceUeIpv4Addr,omitempty"`
	SourceUeIpv6Prefix *Ipv6Prefix `json:"sourceUeIpv6Prefix,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	TargetUeIpv4Addr *string `json:"targetUeIpv4Addr,omitempty"`
	TargetUeIpv6Prefix *Ipv6Prefix `json:"targetUeIpv6Prefix,omitempty"`
	SourceTraRouting NullableRouteToLocation `json:"sourceTraRouting,omitempty"`
	TargetTraRouting NullableRouteToLocation `json:"targetTraRouting,omitempty"`
	// String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042
	UeMac *string `json:"ueMac,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	AdIpv4Addr *string `json:"adIpv4Addr,omitempty"`
	AdIpv6Prefix *Ipv6Prefix `json:"adIpv6Prefix,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	ReIpv4Addr *string `json:"reIpv4Addr,omitempty"`
	ReIpv6Prefix *Ipv6Prefix `json:"reIpv6Prefix,omitempty"`
	PlmnId *PlmnId `json:"plmnId,omitempty"`
	AccType *AccessType `json:"accType,omitempty"`
	// Unsigned integer identifying a PDU session, within the range 0 to 255, as specified in  clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU Session ID is allocated by the  Core Network for UEs not supporting N1 mode, reserved range 64 to 95 is used. PDU Session ID  within the reserved range is only visible in the Core Network.  
	PduSeId *int32 `json:"pduSeId,omitempty"`
	RatType *RatType `json:"ratType,omitempty"`
	DddStatus *DlDataDeliveryStatus `json:"dddStatus,omitempty"`
	DddTraDescriptor *DddTrafficDescriptor `json:"dddTraDescriptor,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	MaxWaitTime *time.Time `json:"maxWaitTime,omitempty"`
	CommFailure *CommunicationFailure `json:"commFailure,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	Ipv4Addr *string `json:"ipv4Addr,omitempty"`
	Ipv6Prefixes []Ipv6Prefix `json:"ipv6Prefixes,omitempty"`
	Ipv6Addrs []Ipv6Addr `json:"ipv6Addrs,omitempty"`
	PduSessType *PduSessionType `json:"pduSessType,omitempty"`
	// Unsigned integer identifying a QoS flow, within the range 0 to 63.
	Qfi *int32 `json:"qfi,omitempty"`
	// String providing an application identifier.
	AppId *string `json:"appId,omitempty"`
	EthfDescs []EthFlowDescription `json:"ethfDescs,omitempty"`
	FDescs []string `json:"fDescs,omitempty"`
	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\").
	Dnn *string `json:"dnn,omitempty"`
	Snssai *Snssai `json:"snssai,omitempty"`
	UlDelays []int32 `json:"ulDelays,omitempty"`
	DlDelays []int32 `json:"dlDelays,omitempty"`
	RtDelays []int32 `json:"rtDelays,omitempty"`
	TimeWindow *TimeWindow `json:"timeWindow,omitempty"`
	SmNasFromUe *SmNasFromUe `json:"smNasFromUe,omitempty"`
	SmNasFromSmf *SmNasFromSmf `json:"smNasFromSmf,omitempty"`
	UpRedTrans *string `json:"upRedTrans,omitempty"`
	SsId *string `json:"ssId,omitempty"`
	BssId *string `json:"bssId,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	StartWlan *time.Time `json:"startWlan,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	EndWlan *time.Time `json:"endWlan,omitempty"`
	PduSessInfos []PduSessionInformation `json:"pduSessInfos,omitempty"`
	UpfInfo *UpfInformation `json:"upfInfo,omitempty"`

	// Added Customized Data
	CustomizedData *CustomizedData `json:"customized_data,omitempty"`
}

type Volume struct {
	Downlink int64 `json:"Downlink,omitempty"`
	Total    int64 `json:"Total,omitempty"`
	Uplink   int64 `json:"Uplink,omitempty"`
}

type CustomUsageReport struct {
	Duration int32  `json:"Duration,omitempty"`
	NoP      Volume `json:"NoP,omitempty"`
	SeId     int32  `json:"SEID,omitempty"`
	Trigger  string `json:"Trigger,omitempty"`
	UrSeqn   int32  `json:"UR-SEQN,omitempty"`
	Volume   Volume `json:"Volume,omitempty"`
}

type CustomizedData struct {
	UsageReport CustomUsageReport `json:"Usage Report,omitempty"`
	Event       string            `json:"event,omitempty"`
	TimeStamp   string            `json:"timeStamp,omitempty"`
}

// NewEventNotification instantiates a new EventNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventNotification(event SmfEventAnyOf, timeStamp time.Time) *EventNotification {
	this := EventNotification{}
	this.Event = event
	this.TimeStamp = timeStamp
	return &this
}

// NewEventNotificationWithDefaults instantiates a new EventNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventNotificationWithDefaults() *EventNotification {
	this := EventNotification{}
	return &this
}

// GetEvent returns the Event field value
func (o *EventNotification) GetEvent() SmfEventAnyOf {
	if o == nil {
		var ret SmfEventAnyOf
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EventNotification) GetEventOk() (*SmfEventAnyOf, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EventNotification) SetEvent(v SmfEventAnyOf) {
	o.Event = v
}

// GetTimeStamp returns the TimeStamp field value
func (o *EventNotification) GetTimeStamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTimeStampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeStamp, true
}

// SetTimeStamp sets field value
func (o *EventNotification) SetTimeStamp(v time.Time) {
	o.TimeStamp = v
}

// GetSupi returns the Supi field value if set, zero value otherwise.
func (o *EventNotification) GetSupi() string {
	if o == nil || o.Supi == nil {
		var ret string
		return ret
	}
	return *o.Supi
}

// GetSupiOk returns a tuple with the Supi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSupiOk() (*string, bool) {
	if o == nil || o.Supi == nil {
		return nil, false
	}
	return o.Supi, true
}

// HasSupi returns a boolean if a field has been set.
func (o *EventNotification) HasSupi() bool {
	if o != nil && o.Supi != nil {
		return true
	}

	return false
}

// SetSupi gets a reference to the given string and assigns it to the Supi field.
func (o *EventNotification) SetSupi(v string) {
	o.Supi = &v
}

// GetGpsi returns the Gpsi field value if set, zero value otherwise.
func (o *EventNotification) GetGpsi() string {
	if o == nil || o.Gpsi == nil {
		var ret string
		return ret
	}
	return *o.Gpsi
}

// GetGpsiOk returns a tuple with the Gpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetGpsiOk() (*string, bool) {
	if o == nil || o.Gpsi == nil {
		return nil, false
	}
	return o.Gpsi, true
}

// HasGpsi returns a boolean if a field has been set.
func (o *EventNotification) HasGpsi() bool {
	if o != nil && o.Gpsi != nil {
		return true
	}

	return false
}

// SetGpsi gets a reference to the given string and assigns it to the Gpsi field.
func (o *EventNotification) SetGpsi(v string) {
	o.Gpsi = &v
}

// GetUeIpAddr returns the UeIpAddr field value if set, zero value otherwise.
func (o *EventNotification) GetUeIpAddr() IpAddr {
	if o == nil || o.UeIpAddr == nil {
		var ret IpAddr
		return ret
	}
	return *o.UeIpAddr
}

// GetUeIpAddrOk returns a tuple with the UeIpAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetUeIpAddrOk() (*IpAddr, bool) {
	if o == nil || o.UeIpAddr == nil {
		return nil, false
	}
	return o.UeIpAddr, true
}

// HasUeIpAddr returns a boolean if a field has been set.
func (o *EventNotification) HasUeIpAddr() bool {
	if o != nil && o.UeIpAddr != nil {
		return true
	}

	return false
}

// SetUeIpAddr gets a reference to the given IpAddr and assigns it to the UeIpAddr field.
func (o *EventNotification) SetUeIpAddr(v IpAddr) {
	o.UeIpAddr = &v
}

// GetTransacInfos returns the TransacInfos field value if set, zero value otherwise.
func (o *EventNotification) GetTransacInfos() []TransactionInfo {
	if o == nil || o.TransacInfos == nil {
		var ret []TransactionInfo
		return ret
	}
	return o.TransacInfos
}

// GetTransacInfosOk returns a tuple with the TransacInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTransacInfosOk() ([]TransactionInfo, bool) {
	if o == nil || o.TransacInfos == nil {
		return nil, false
	}
	return o.TransacInfos, true
}

// HasTransacInfos returns a boolean if a field has been set.
func (o *EventNotification) HasTransacInfos() bool {
	if o != nil && o.TransacInfos != nil {
		return true
	}

	return false
}

// SetTransacInfos gets a reference to the given []TransactionInfo and assigns it to the TransacInfos field.
func (o *EventNotification) SetTransacInfos(v []TransactionInfo) {
	o.TransacInfos = v
}

// GetSourceDnai returns the SourceDnai field value if set, zero value otherwise.
func (o *EventNotification) GetSourceDnai() string {
	if o == nil || o.SourceDnai == nil {
		var ret string
		return ret
	}
	return *o.SourceDnai
}

// GetSourceDnaiOk returns a tuple with the SourceDnai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSourceDnaiOk() (*string, bool) {
	if o == nil || o.SourceDnai == nil {
		return nil, false
	}
	return o.SourceDnai, true
}

// HasSourceDnai returns a boolean if a field has been set.
func (o *EventNotification) HasSourceDnai() bool {
	if o != nil && o.SourceDnai != nil {
		return true
	}

	return false
}

// SetSourceDnai gets a reference to the given string and assigns it to the SourceDnai field.
func (o *EventNotification) SetSourceDnai(v string) {
	o.SourceDnai = &v
}

// GetTargetDnai returns the TargetDnai field value if set, zero value otherwise.
func (o *EventNotification) GetTargetDnai() string {
	if o == nil || o.TargetDnai == nil {
		var ret string
		return ret
	}
	return *o.TargetDnai
}

// GetTargetDnaiOk returns a tuple with the TargetDnai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTargetDnaiOk() (*string, bool) {
	if o == nil || o.TargetDnai == nil {
		return nil, false
	}
	return o.TargetDnai, true
}

// HasTargetDnai returns a boolean if a field has been set.
func (o *EventNotification) HasTargetDnai() bool {
	if o != nil && o.TargetDnai != nil {
		return true
	}

	return false
}

// SetTargetDnai gets a reference to the given string and assigns it to the TargetDnai field.
func (o *EventNotification) SetTargetDnai(v string) {
	o.TargetDnai = &v
}

// GetDnaiChgType returns the DnaiChgType field value if set, zero value otherwise.
func (o *EventNotification) GetDnaiChgType() DnaiChangeType {
	if o == nil || o.DnaiChgType == nil {
		var ret DnaiChangeType
		return ret
	}
	return *o.DnaiChgType
}

// GetDnaiChgTypeOk returns a tuple with the DnaiChgType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetDnaiChgTypeOk() (*DnaiChangeType, bool) {
	if o == nil || o.DnaiChgType == nil {
		return nil, false
	}
	return o.DnaiChgType, true
}

// HasDnaiChgType returns a boolean if a field has been set.
func (o *EventNotification) HasDnaiChgType() bool {
	if o != nil && o.DnaiChgType != nil {
		return true
	}

	return false
}

// SetDnaiChgType gets a reference to the given DnaiChangeType and assigns it to the DnaiChgType field.
func (o *EventNotification) SetDnaiChgType(v DnaiChangeType) {
	o.DnaiChgType = &v
}

// GetSourceUeIpv4Addr returns the SourceUeIpv4Addr field value if set, zero value otherwise.
func (o *EventNotification) GetSourceUeIpv4Addr() string {
	if o == nil || o.SourceUeIpv4Addr == nil {
		var ret string
		return ret
	}
	return *o.SourceUeIpv4Addr
}

// GetSourceUeIpv4AddrOk returns a tuple with the SourceUeIpv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSourceUeIpv4AddrOk() (*string, bool) {
	if o == nil || o.SourceUeIpv4Addr == nil {
		return nil, false
	}
	return o.SourceUeIpv4Addr, true
}

// HasSourceUeIpv4Addr returns a boolean if a field has been set.
func (o *EventNotification) HasSourceUeIpv4Addr() bool {
	if o != nil && o.SourceUeIpv4Addr != nil {
		return true
	}

	return false
}

// SetSourceUeIpv4Addr gets a reference to the given string and assigns it to the SourceUeIpv4Addr field.
func (o *EventNotification) SetSourceUeIpv4Addr(v string) {
	o.SourceUeIpv4Addr = &v
}

// GetSourceUeIpv6Prefix returns the SourceUeIpv6Prefix field value if set, zero value otherwise.
func (o *EventNotification) GetSourceUeIpv6Prefix() Ipv6Prefix {
	if o == nil || o.SourceUeIpv6Prefix == nil {
		var ret Ipv6Prefix
		return ret
	}
	return *o.SourceUeIpv6Prefix
}

// GetSourceUeIpv6PrefixOk returns a tuple with the SourceUeIpv6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSourceUeIpv6PrefixOk() (*Ipv6Prefix, bool) {
	if o == nil || o.SourceUeIpv6Prefix == nil {
		return nil, false
	}
	return o.SourceUeIpv6Prefix, true
}

// HasSourceUeIpv6Prefix returns a boolean if a field has been set.
func (o *EventNotification) HasSourceUeIpv6Prefix() bool {
	if o != nil && o.SourceUeIpv6Prefix != nil {
		return true
	}

	return false
}

// SetSourceUeIpv6Prefix gets a reference to the given Ipv6Prefix and assigns it to the SourceUeIpv6Prefix field.
func (o *EventNotification) SetSourceUeIpv6Prefix(v Ipv6Prefix) {
	o.SourceUeIpv6Prefix = &v
}

// GetTargetUeIpv4Addr returns the TargetUeIpv4Addr field value if set, zero value otherwise.
func (o *EventNotification) GetTargetUeIpv4Addr() string {
	if o == nil || o.TargetUeIpv4Addr == nil {
		var ret string
		return ret
	}
	return *o.TargetUeIpv4Addr
}

// GetTargetUeIpv4AddrOk returns a tuple with the TargetUeIpv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTargetUeIpv4AddrOk() (*string, bool) {
	if o == nil || o.TargetUeIpv4Addr == nil {
		return nil, false
	}
	return o.TargetUeIpv4Addr, true
}

// HasTargetUeIpv4Addr returns a boolean if a field has been set.
func (o *EventNotification) HasTargetUeIpv4Addr() bool {
	if o != nil && o.TargetUeIpv4Addr != nil {
		return true
	}

	return false
}

// SetTargetUeIpv4Addr gets a reference to the given string and assigns it to the TargetUeIpv4Addr field.
func (o *EventNotification) SetTargetUeIpv4Addr(v string) {
	o.TargetUeIpv4Addr = &v
}

// GetTargetUeIpv6Prefix returns the TargetUeIpv6Prefix field value if set, zero value otherwise.
func (o *EventNotification) GetTargetUeIpv6Prefix() Ipv6Prefix {
	if o == nil || o.TargetUeIpv6Prefix == nil {
		var ret Ipv6Prefix
		return ret
	}
	return *o.TargetUeIpv6Prefix
}

// GetTargetUeIpv6PrefixOk returns a tuple with the TargetUeIpv6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTargetUeIpv6PrefixOk() (*Ipv6Prefix, bool) {
	if o == nil || o.TargetUeIpv6Prefix == nil {
		return nil, false
	}
	return o.TargetUeIpv6Prefix, true
}

// HasTargetUeIpv6Prefix returns a boolean if a field has been set.
func (o *EventNotification) HasTargetUeIpv6Prefix() bool {
	if o != nil && o.TargetUeIpv6Prefix != nil {
		return true
	}

	return false
}

// SetTargetUeIpv6Prefix gets a reference to the given Ipv6Prefix and assigns it to the TargetUeIpv6Prefix field.
func (o *EventNotification) SetTargetUeIpv6Prefix(v Ipv6Prefix) {
	o.TargetUeIpv6Prefix = &v
}

// GetSourceTraRouting returns the SourceTraRouting field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventNotification) GetSourceTraRouting() RouteToLocation {
	if o == nil || o.SourceTraRouting.Get() == nil {
		var ret RouteToLocation
		return ret
	}
	return *o.SourceTraRouting.Get()
}

// GetSourceTraRoutingOk returns a tuple with the SourceTraRouting field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventNotification) GetSourceTraRoutingOk() (*RouteToLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceTraRouting.Get(), o.SourceTraRouting.IsSet()
}

// HasSourceTraRouting returns a boolean if a field has been set.
func (o *EventNotification) HasSourceTraRouting() bool {
	if o != nil && o.SourceTraRouting.IsSet() {
		return true
	}

	return false
}

// SetSourceTraRouting gets a reference to the given NullableRouteToLocation and assigns it to the SourceTraRouting field.
func (o *EventNotification) SetSourceTraRouting(v RouteToLocation) {
	o.SourceTraRouting.Set(&v)
}
// SetSourceTraRoutingNil sets the value for SourceTraRouting to be an explicit nil
func (o *EventNotification) SetSourceTraRoutingNil() {
	o.SourceTraRouting.Set(nil)
}

// UnsetSourceTraRouting ensures that no value is present for SourceTraRouting, not even an explicit nil
func (o *EventNotification) UnsetSourceTraRouting() {
	o.SourceTraRouting.Unset()
}

// GetTargetTraRouting returns the TargetTraRouting field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EventNotification) GetTargetTraRouting() RouteToLocation {
	if o == nil || o.TargetTraRouting.Get() == nil {
		var ret RouteToLocation
		return ret
	}
	return *o.TargetTraRouting.Get()
}

// GetTargetTraRoutingOk returns a tuple with the TargetTraRouting field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventNotification) GetTargetTraRoutingOk() (*RouteToLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetTraRouting.Get(), o.TargetTraRouting.IsSet()
}

// HasTargetTraRouting returns a boolean if a field has been set.
func (o *EventNotification) HasTargetTraRouting() bool {
	if o != nil && o.TargetTraRouting.IsSet() {
		return true
	}

	return false
}

// SetTargetTraRouting gets a reference to the given NullableRouteToLocation and assigns it to the TargetTraRouting field.
func (o *EventNotification) SetTargetTraRouting(v RouteToLocation) {
	o.TargetTraRouting.Set(&v)
}
// SetTargetTraRoutingNil sets the value for TargetTraRouting to be an explicit nil
func (o *EventNotification) SetTargetTraRoutingNil() {
	o.TargetTraRouting.Set(nil)
}

// UnsetTargetTraRouting ensures that no value is present for TargetTraRouting, not even an explicit nil
func (o *EventNotification) UnsetTargetTraRouting() {
	o.TargetTraRouting.Unset()
}

// GetUeMac returns the UeMac field value if set, zero value otherwise.
func (o *EventNotification) GetUeMac() string {
	if o == nil || o.UeMac == nil {
		var ret string
		return ret
	}
	return *o.UeMac
}

// GetUeMacOk returns a tuple with the UeMac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetUeMacOk() (*string, bool) {
	if o == nil || o.UeMac == nil {
		return nil, false
	}
	return o.UeMac, true
}

// HasUeMac returns a boolean if a field has been set.
func (o *EventNotification) HasUeMac() bool {
	if o != nil && o.UeMac != nil {
		return true
	}

	return false
}

// SetUeMac gets a reference to the given string and assigns it to the UeMac field.
func (o *EventNotification) SetUeMac(v string) {
	o.UeMac = &v
}

// GetAdIpv4Addr returns the AdIpv4Addr field value if set, zero value otherwise.
func (o *EventNotification) GetAdIpv4Addr() string {
	if o == nil || o.AdIpv4Addr == nil {
		var ret string
		return ret
	}
	return *o.AdIpv4Addr
}

// GetAdIpv4AddrOk returns a tuple with the AdIpv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetAdIpv4AddrOk() (*string, bool) {
	if o == nil || o.AdIpv4Addr == nil {
		return nil, false
	}
	return o.AdIpv4Addr, true
}

// HasAdIpv4Addr returns a boolean if a field has been set.
func (o *EventNotification) HasAdIpv4Addr() bool {
	if o != nil && o.AdIpv4Addr != nil {
		return true
	}

	return false
}

// SetAdIpv4Addr gets a reference to the given string and assigns it to the AdIpv4Addr field.
func (o *EventNotification) SetAdIpv4Addr(v string) {
	o.AdIpv4Addr = &v
}

// GetAdIpv6Prefix returns the AdIpv6Prefix field value if set, zero value otherwise.
func (o *EventNotification) GetAdIpv6Prefix() Ipv6Prefix {
	if o == nil || o.AdIpv6Prefix == nil {
		var ret Ipv6Prefix
		return ret
	}
	return *o.AdIpv6Prefix
}

// GetAdIpv6PrefixOk returns a tuple with the AdIpv6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetAdIpv6PrefixOk() (*Ipv6Prefix, bool) {
	if o == nil || o.AdIpv6Prefix == nil {
		return nil, false
	}
	return o.AdIpv6Prefix, true
}

// HasAdIpv6Prefix returns a boolean if a field has been set.
func (o *EventNotification) HasAdIpv6Prefix() bool {
	if o != nil && o.AdIpv6Prefix != nil {
		return true
	}

	return false
}

// SetAdIpv6Prefix gets a reference to the given Ipv6Prefix and assigns it to the AdIpv6Prefix field.
func (o *EventNotification) SetAdIpv6Prefix(v Ipv6Prefix) {
	o.AdIpv6Prefix = &v
}

// GetReIpv4Addr returns the ReIpv4Addr field value if set, zero value otherwise.
func (o *EventNotification) GetReIpv4Addr() string {
	if o == nil || o.ReIpv4Addr == nil {
		var ret string
		return ret
	}
	return *o.ReIpv4Addr
}

// GetReIpv4AddrOk returns a tuple with the ReIpv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetReIpv4AddrOk() (*string, bool) {
	if o == nil || o.ReIpv4Addr == nil {
		return nil, false
	}
	return o.ReIpv4Addr, true
}

// HasReIpv4Addr returns a boolean if a field has been set.
func (o *EventNotification) HasReIpv4Addr() bool {
	if o != nil && o.ReIpv4Addr != nil {
		return true
	}

	return false
}

// SetReIpv4Addr gets a reference to the given string and assigns it to the ReIpv4Addr field.
func (o *EventNotification) SetReIpv4Addr(v string) {
	o.ReIpv4Addr = &v
}

// GetReIpv6Prefix returns the ReIpv6Prefix field value if set, zero value otherwise.
func (o *EventNotification) GetReIpv6Prefix() Ipv6Prefix {
	if o == nil || o.ReIpv6Prefix == nil {
		var ret Ipv6Prefix
		return ret
	}
	return *o.ReIpv6Prefix
}

// GetReIpv6PrefixOk returns a tuple with the ReIpv6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetReIpv6PrefixOk() (*Ipv6Prefix, bool) {
	if o == nil || o.ReIpv6Prefix == nil {
		return nil, false
	}
	return o.ReIpv6Prefix, true
}

// HasReIpv6Prefix returns a boolean if a field has been set.
func (o *EventNotification) HasReIpv6Prefix() bool {
	if o != nil && o.ReIpv6Prefix != nil {
		return true
	}

	return false
}

// SetReIpv6Prefix gets a reference to the given Ipv6Prefix and assigns it to the ReIpv6Prefix field.
func (o *EventNotification) SetReIpv6Prefix(v Ipv6Prefix) {
	o.ReIpv6Prefix = &v
}

// GetPlmnId returns the PlmnId field value if set, zero value otherwise.
func (o *EventNotification) GetPlmnId() PlmnId {
	if o == nil || o.PlmnId == nil {
		var ret PlmnId
		return ret
	}
	return *o.PlmnId
}

// GetPlmnIdOk returns a tuple with the PlmnId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetPlmnIdOk() (*PlmnId, bool) {
	if o == nil || o.PlmnId == nil {
		return nil, false
	}
	return o.PlmnId, true
}

// HasPlmnId returns a boolean if a field has been set.
func (o *EventNotification) HasPlmnId() bool {
	if o != nil && o.PlmnId != nil {
		return true
	}

	return false
}

// SetPlmnId gets a reference to the given PlmnId and assigns it to the PlmnId field.
func (o *EventNotification) SetPlmnId(v PlmnId) {
	o.PlmnId = &v
}

// GetAccType returns the AccType field value if set, zero value otherwise.
func (o *EventNotification) GetAccType() AccessType {
	if o == nil || o.AccType == nil {
		var ret AccessType
		return ret
	}
	return *o.AccType
}

// GetAccTypeOk returns a tuple with the AccType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetAccTypeOk() (*AccessType, bool) {
	if o == nil || o.AccType == nil {
		return nil, false
	}
	return o.AccType, true
}

// HasAccType returns a boolean if a field has been set.
func (o *EventNotification) HasAccType() bool {
	if o != nil && o.AccType != nil {
		return true
	}

	return false
}

// SetAccType gets a reference to the given AccessType and assigns it to the AccType field.
func (o *EventNotification) SetAccType(v AccessType) {
	o.AccType = &v
}

// GetPduSeId returns the PduSeId field value if set, zero value otherwise.
func (o *EventNotification) GetPduSeId() int32 {
	if o == nil || o.PduSeId == nil {
		var ret int32
		return ret
	}
	return *o.PduSeId
}

// GetPduSeIdOk returns a tuple with the PduSeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetPduSeIdOk() (*int32, bool) {
	if o == nil || o.PduSeId == nil {
		return nil, false
	}
	return o.PduSeId, true
}

// HasPduSeId returns a boolean if a field has been set.
func (o *EventNotification) HasPduSeId() bool {
	if o != nil && o.PduSeId != nil {
		return true
	}

	return false
}

// SetPduSeId gets a reference to the given int32 and assigns it to the PduSeId field.
func (o *EventNotification) SetPduSeId(v int32) {
	o.PduSeId = &v
}

// GetRatType returns the RatType field value if set, zero value otherwise.
func (o *EventNotification) GetRatType() RatType {
	if o == nil || o.RatType == nil {
		var ret RatType
		return ret
	}
	return *o.RatType
}

// GetRatTypeOk returns a tuple with the RatType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetRatTypeOk() (*RatType, bool) {
	if o == nil || o.RatType == nil {
		return nil, false
	}
	return o.RatType, true
}

// HasRatType returns a boolean if a field has been set.
func (o *EventNotification) HasRatType() bool {
	if o != nil && o.RatType != nil {
		return true
	}

	return false
}

// SetRatType gets a reference to the given RatType and assigns it to the RatType field.
func (o *EventNotification) SetRatType(v RatType) {
	o.RatType = &v
}

// GetDddStatus returns the DddStatus field value if set, zero value otherwise.
func (o *EventNotification) GetDddStatus() DlDataDeliveryStatus {
	if o == nil || o.DddStatus == nil {
		var ret DlDataDeliveryStatus
		return ret
	}
	return *o.DddStatus
}

// GetDddStatusOk returns a tuple with the DddStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetDddStatusOk() (*DlDataDeliveryStatus, bool) {
	if o == nil || o.DddStatus == nil {
		return nil, false
	}
	return o.DddStatus, true
}

// HasDddStatus returns a boolean if a field has been set.
func (o *EventNotification) HasDddStatus() bool {
	if o != nil && o.DddStatus != nil {
		return true
	}

	return false
}

// SetDddStatus gets a reference to the given DlDataDeliveryStatus and assigns it to the DddStatus field.
func (o *EventNotification) SetDddStatus(v DlDataDeliveryStatus) {
	o.DddStatus = &v
}

// GetDddTraDescriptor returns the DddTraDescriptor field value if set, zero value otherwise.
func (o *EventNotification) GetDddTraDescriptor() DddTrafficDescriptor {
	if o == nil || o.DddTraDescriptor == nil {
		var ret DddTrafficDescriptor
		return ret
	}
	return *o.DddTraDescriptor
}

// GetDddTraDescriptorOk returns a tuple with the DddTraDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetDddTraDescriptorOk() (*DddTrafficDescriptor, bool) {
	if o == nil || o.DddTraDescriptor == nil {
		return nil, false
	}
	return o.DddTraDescriptor, true
}

// HasDddTraDescriptor returns a boolean if a field has been set.
func (o *EventNotification) HasDddTraDescriptor() bool {
	if o != nil && o.DddTraDescriptor != nil {
		return true
	}

	return false
}

// SetDddTraDescriptor gets a reference to the given DddTrafficDescriptor and assigns it to the DddTraDescriptor field.
func (o *EventNotification) SetDddTraDescriptor(v DddTrafficDescriptor) {
	o.DddTraDescriptor = &v
}

// GetMaxWaitTime returns the MaxWaitTime field value if set, zero value otherwise.
func (o *EventNotification) GetMaxWaitTime() time.Time {
	if o == nil || o.MaxWaitTime == nil {
		var ret time.Time
		return ret
	}
	return *o.MaxWaitTime
}

// GetMaxWaitTimeOk returns a tuple with the MaxWaitTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetMaxWaitTimeOk() (*time.Time, bool) {
	if o == nil || o.MaxWaitTime == nil {
		return nil, false
	}
	return o.MaxWaitTime, true
}

// HasMaxWaitTime returns a boolean if a field has been set.
func (o *EventNotification) HasMaxWaitTime() bool {
	if o != nil && o.MaxWaitTime != nil {
		return true
	}

	return false
}

// SetMaxWaitTime gets a reference to the given time.Time and assigns it to the MaxWaitTime field.
func (o *EventNotification) SetMaxWaitTime(v time.Time) {
	o.MaxWaitTime = &v
}

// GetCommFailure returns the CommFailure field value if set, zero value otherwise.
func (o *EventNotification) GetCommFailure() CommunicationFailure {
	if o == nil || o.CommFailure == nil {
		var ret CommunicationFailure
		return ret
	}
	return *o.CommFailure
}

// GetCommFailureOk returns a tuple with the CommFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetCommFailureOk() (*CommunicationFailure, bool) {
	if o == nil || o.CommFailure == nil {
		return nil, false
	}
	return o.CommFailure, true
}

// HasCommFailure returns a boolean if a field has been set.
func (o *EventNotification) HasCommFailure() bool {
	if o != nil && o.CommFailure != nil {
		return true
	}

	return false
}

// SetCommFailure gets a reference to the given CommunicationFailure and assigns it to the CommFailure field.
func (o *EventNotification) SetCommFailure(v CommunicationFailure) {
	o.CommFailure = &v
}

// GetIpv4Addr returns the Ipv4Addr field value if set, zero value otherwise.
func (o *EventNotification) GetIpv4Addr() string {
	if o == nil || o.Ipv4Addr == nil {
		var ret string
		return ret
	}
	return *o.Ipv4Addr
}

// GetIpv4AddrOk returns a tuple with the Ipv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetIpv4AddrOk() (*string, bool) {
	if o == nil || o.Ipv4Addr == nil {
		return nil, false
	}
	return o.Ipv4Addr, true
}

// HasIpv4Addr returns a boolean if a field has been set.
func (o *EventNotification) HasIpv4Addr() bool {
	if o != nil && o.Ipv4Addr != nil {
		return true
	}

	return false
}

// SetIpv4Addr gets a reference to the given string and assigns it to the Ipv4Addr field.
func (o *EventNotification) SetIpv4Addr(v string) {
	o.Ipv4Addr = &v
}

// GetIpv6Prefixes returns the Ipv6Prefixes field value if set, zero value otherwise.
func (o *EventNotification) GetIpv6Prefixes() []Ipv6Prefix {
	if o == nil || o.Ipv6Prefixes == nil {
		var ret []Ipv6Prefix
		return ret
	}
	return o.Ipv6Prefixes
}

// GetIpv6PrefixesOk returns a tuple with the Ipv6Prefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetIpv6PrefixesOk() ([]Ipv6Prefix, bool) {
	if o == nil || o.Ipv6Prefixes == nil {
		return nil, false
	}
	return o.Ipv6Prefixes, true
}

// HasIpv6Prefixes returns a boolean if a field has been set.
func (o *EventNotification) HasIpv6Prefixes() bool {
	if o != nil && o.Ipv6Prefixes != nil {
		return true
	}

	return false
}

// SetIpv6Prefixes gets a reference to the given []Ipv6Prefix and assigns it to the Ipv6Prefixes field.
func (o *EventNotification) SetIpv6Prefixes(v []Ipv6Prefix) {
	o.Ipv6Prefixes = v
}

// GetIpv6Addrs returns the Ipv6Addrs field value if set, zero value otherwise.
func (o *EventNotification) GetIpv6Addrs() []Ipv6Addr {
	if o == nil || o.Ipv6Addrs == nil {
		var ret []Ipv6Addr
		return ret
	}
	return o.Ipv6Addrs
}

// GetIpv6AddrsOk returns a tuple with the Ipv6Addrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetIpv6AddrsOk() ([]Ipv6Addr, bool) {
	if o == nil || o.Ipv6Addrs == nil {
		return nil, false
	}
	return o.Ipv6Addrs, true
}

// HasIpv6Addrs returns a boolean if a field has been set.
func (o *EventNotification) HasIpv6Addrs() bool {
	if o != nil && o.Ipv6Addrs != nil {
		return true
	}

	return false
}

// SetIpv6Addrs gets a reference to the given []Ipv6Addr and assigns it to the Ipv6Addrs field.
func (o *EventNotification) SetIpv6Addrs(v []Ipv6Addr) {
	o.Ipv6Addrs = v
}

// GetPduSessType returns the PduSessType field value if set, zero value otherwise.
func (o *EventNotification) GetPduSessType() PduSessionType {
	if o == nil || o.PduSessType == nil {
		var ret PduSessionType
		return ret
	}
	return *o.PduSessType
}

// GetPduSessTypeOk returns a tuple with the PduSessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetPduSessTypeOk() (*PduSessionType, bool) {
	if o == nil || o.PduSessType == nil {
		return nil, false
	}
	return o.PduSessType, true
}

// HasPduSessType returns a boolean if a field has been set.
func (o *EventNotification) HasPduSessType() bool {
	if o != nil && o.PduSessType != nil {
		return true
	}

	return false
}

// SetPduSessType gets a reference to the given PduSessionType and assigns it to the PduSessType field.
func (o *EventNotification) SetPduSessType(v PduSessionType) {
	o.PduSessType = &v
}

// GetQfi returns the Qfi field value if set, zero value otherwise.
func (o *EventNotification) GetQfi() int32 {
	if o == nil || o.Qfi == nil {
		var ret int32
		return ret
	}
	return *o.Qfi
}

// GetQfiOk returns a tuple with the Qfi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetQfiOk() (*int32, bool) {
	if o == nil || o.Qfi == nil {
		return nil, false
	}
	return o.Qfi, true
}

// HasQfi returns a boolean if a field has been set.
func (o *EventNotification) HasQfi() bool {
	if o != nil && o.Qfi != nil {
		return true
	}

	return false
}

// SetQfi gets a reference to the given int32 and assigns it to the Qfi field.
func (o *EventNotification) SetQfi(v int32) {
	o.Qfi = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *EventNotification) GetAppId() string {
	if o == nil || o.AppId == nil {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetAppIdOk() (*string, bool) {
	if o == nil || o.AppId == nil {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *EventNotification) HasAppId() bool {
	if o != nil && o.AppId != nil {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *EventNotification) SetAppId(v string) {
	o.AppId = &v
}

// GetEthfDescs returns the EthfDescs field value if set, zero value otherwise.
func (o *EventNotification) GetEthfDescs() []EthFlowDescription {
	if o == nil || o.EthfDescs == nil {
		var ret []EthFlowDescription
		return ret
	}
	return o.EthfDescs
}

// GetEthfDescsOk returns a tuple with the EthfDescs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetEthfDescsOk() ([]EthFlowDescription, bool) {
	if o == nil || o.EthfDescs == nil {
		return nil, false
	}
	return o.EthfDescs, true
}

// HasEthfDescs returns a boolean if a field has been set.
func (o *EventNotification) HasEthfDescs() bool {
	if o != nil && o.EthfDescs != nil {
		return true
	}

	return false
}

// SetEthfDescs gets a reference to the given []EthFlowDescription and assigns it to the EthfDescs field.
func (o *EventNotification) SetEthfDescs(v []EthFlowDescription) {
	o.EthfDescs = v
}

// GetFDescs returns the FDescs field value if set, zero value otherwise.
func (o *EventNotification) GetFDescs() []string {
	if o == nil || o.FDescs == nil {
		var ret []string
		return ret
	}
	return o.FDescs
}

// GetFDescsOk returns a tuple with the FDescs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetFDescsOk() ([]string, bool) {
	if o == nil || o.FDescs == nil {
		return nil, false
	}
	return o.FDescs, true
}

// HasFDescs returns a boolean if a field has been set.
func (o *EventNotification) HasFDescs() bool {
	if o != nil && o.FDescs != nil {
		return true
	}

	return false
}

// SetFDescs gets a reference to the given []string and assigns it to the FDescs field.
func (o *EventNotification) SetFDescs(v []string) {
	o.FDescs = v
}

// GetDnn returns the Dnn field value if set, zero value otherwise.
func (o *EventNotification) GetDnn() string {
	if o == nil || o.Dnn == nil {
		var ret string
		return ret
	}
	return *o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetDnnOk() (*string, bool) {
	if o == nil || o.Dnn == nil {
		return nil, false
	}
	return o.Dnn, true
}

// HasDnn returns a boolean if a field has been set.
func (o *EventNotification) HasDnn() bool {
	if o != nil && o.Dnn != nil {
		return true
	}

	return false
}

// SetDnn gets a reference to the given string and assigns it to the Dnn field.
func (o *EventNotification) SetDnn(v string) {
	o.Dnn = &v
}

// GetSnssai returns the Snssai field value if set, zero value otherwise.
func (o *EventNotification) GetSnssai() Snssai {
	if o == nil || o.Snssai == nil {
		var ret Snssai
		return ret
	}
	return *o.Snssai
}

// GetSnssaiOk returns a tuple with the Snssai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSnssaiOk() (*Snssai, bool) {
	if o == nil || o.Snssai == nil {
		return nil, false
	}
	return o.Snssai, true
}

// HasSnssai returns a boolean if a field has been set.
func (o *EventNotification) HasSnssai() bool {
	if o != nil && o.Snssai != nil {
		return true
	}

	return false
}

// SetSnssai gets a reference to the given Snssai and assigns it to the Snssai field.
func (o *EventNotification) SetSnssai(v Snssai) {
	o.Snssai = &v
}

// GetUlDelays returns the UlDelays field value if set, zero value otherwise.
func (o *EventNotification) GetUlDelays() []int32 {
	if o == nil || o.UlDelays == nil {
		var ret []int32
		return ret
	}
	return o.UlDelays
}

// GetUlDelaysOk returns a tuple with the UlDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetUlDelaysOk() ([]int32, bool) {
	if o == nil || o.UlDelays == nil {
		return nil, false
	}
	return o.UlDelays, true
}

// HasUlDelays returns a boolean if a field has been set.
func (o *EventNotification) HasUlDelays() bool {
	if o != nil && o.UlDelays != nil {
		return true
	}

	return false
}

// SetUlDelays gets a reference to the given []int32 and assigns it to the UlDelays field.
func (o *EventNotification) SetUlDelays(v []int32) {
	o.UlDelays = v
}

// GetDlDelays returns the DlDelays field value if set, zero value otherwise.
func (o *EventNotification) GetDlDelays() []int32 {
	if o == nil || o.DlDelays == nil {
		var ret []int32
		return ret
	}
	return o.DlDelays
}

// GetDlDelaysOk returns a tuple with the DlDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetDlDelaysOk() ([]int32, bool) {
	if o == nil || o.DlDelays == nil {
		return nil, false
	}
	return o.DlDelays, true
}

// HasDlDelays returns a boolean if a field has been set.
func (o *EventNotification) HasDlDelays() bool {
	if o != nil && o.DlDelays != nil {
		return true
	}

	return false
}

// SetDlDelays gets a reference to the given []int32 and assigns it to the DlDelays field.
func (o *EventNotification) SetDlDelays(v []int32) {
	o.DlDelays = v
}

// GetRtDelays returns the RtDelays field value if set, zero value otherwise.
func (o *EventNotification) GetRtDelays() []int32 {
	if o == nil || o.RtDelays == nil {
		var ret []int32
		return ret
	}
	return o.RtDelays
}

// GetRtDelaysOk returns a tuple with the RtDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetRtDelaysOk() ([]int32, bool) {
	if o == nil || o.RtDelays == nil {
		return nil, false
	}
	return o.RtDelays, true
}

// HasRtDelays returns a boolean if a field has been set.
func (o *EventNotification) HasRtDelays() bool {
	if o != nil && o.RtDelays != nil {
		return true
	}

	return false
}

// SetRtDelays gets a reference to the given []int32 and assigns it to the RtDelays field.
func (o *EventNotification) SetRtDelays(v []int32) {
	o.RtDelays = v
}

// GetTimeWindow returns the TimeWindow field value if set, zero value otherwise.
func (o *EventNotification) GetTimeWindow() TimeWindow {
	if o == nil || o.TimeWindow == nil {
		var ret TimeWindow
		return ret
	}
	return *o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetTimeWindowOk() (*TimeWindow, bool) {
	if o == nil || o.TimeWindow == nil {
		return nil, false
	}
	return o.TimeWindow, true
}

// HasTimeWindow returns a boolean if a field has been set.
func (o *EventNotification) HasTimeWindow() bool {
	if o != nil && o.TimeWindow != nil {
		return true
	}

	return false
}

// SetTimeWindow gets a reference to the given TimeWindow and assigns it to the TimeWindow field.
func (o *EventNotification) SetTimeWindow(v TimeWindow) {
	o.TimeWindow = &v
}

// GetSmNasFromUe returns the SmNasFromUe field value if set, zero value otherwise.
func (o *EventNotification) GetSmNasFromUe() SmNasFromUe {
	if o == nil || o.SmNasFromUe == nil {
		var ret SmNasFromUe
		return ret
	}
	return *o.SmNasFromUe
}

// GetSmNasFromUeOk returns a tuple with the SmNasFromUe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSmNasFromUeOk() (*SmNasFromUe, bool) {
	if o == nil || o.SmNasFromUe == nil {
		return nil, false
	}
	return o.SmNasFromUe, true
}

// HasSmNasFromUe returns a boolean if a field has been set.
func (o *EventNotification) HasSmNasFromUe() bool {
	if o != nil && o.SmNasFromUe != nil {
		return true
	}

	return false
}

// SetSmNasFromUe gets a reference to the given SmNasFromUe and assigns it to the SmNasFromUe field.
func (o *EventNotification) SetSmNasFromUe(v SmNasFromUe) {
	o.SmNasFromUe = &v
}

// GetSmNasFromSmf returns the SmNasFromSmf field value if set, zero value otherwise.
func (o *EventNotification) GetSmNasFromSmf() SmNasFromSmf {
	if o == nil || o.SmNasFromSmf == nil {
		var ret SmNasFromSmf
		return ret
	}
	return *o.SmNasFromSmf
}

// GetSmNasFromSmfOk returns a tuple with the SmNasFromSmf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSmNasFromSmfOk() (*SmNasFromSmf, bool) {
	if o == nil || o.SmNasFromSmf == nil {
		return nil, false
	}
	return o.SmNasFromSmf, true
}

// HasSmNasFromSmf returns a boolean if a field has been set.
func (o *EventNotification) HasSmNasFromSmf() bool {
	if o != nil && o.SmNasFromSmf != nil {
		return true
	}

	return false
}

// SetSmNasFromSmf gets a reference to the given SmNasFromSmf and assigns it to the SmNasFromSmf field.
func (o *EventNotification) SetSmNasFromSmf(v SmNasFromSmf) {
	o.SmNasFromSmf = &v
}

// GetUpRedTrans returns the UpRedTrans field value if set, zero value otherwise.
func (o *EventNotification) GetUpRedTrans() string {
	if o == nil || o.UpRedTrans == nil {
		var ret string
		return ret
	}
	return *o.UpRedTrans
}

// GetUpRedTransOk returns a tuple with the UpRedTrans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetUpRedTransOk() (*string, bool) {
	if o == nil || o.UpRedTrans == nil {
		return nil, false
	}
	return o.UpRedTrans, true
}

// HasUpRedTrans returns a boolean if a field has been set.
func (o *EventNotification) HasUpRedTrans() bool {
	if o != nil && o.UpRedTrans != nil {
		return true
	}

	return false
}

// SetUpRedTrans gets a reference to the given string and assigns it to the UpRedTrans field.
func (o *EventNotification) SetUpRedTrans(v string) {
	o.UpRedTrans = &v
}

// GetSsId returns the SsId field value if set, zero value otherwise.
func (o *EventNotification) GetSsId() string {
	if o == nil || o.SsId == nil {
		var ret string
		return ret
	}
	return *o.SsId
}

// GetSsIdOk returns a tuple with the SsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetSsIdOk() (*string, bool) {
	if o == nil || o.SsId == nil {
		return nil, false
	}
	return o.SsId, true
}

// HasSsId returns a boolean if a field has been set.
func (o *EventNotification) HasSsId() bool {
	if o != nil && o.SsId != nil {
		return true
	}

	return false
}

// SetSsId gets a reference to the given string and assigns it to the SsId field.
func (o *EventNotification) SetSsId(v string) {
	o.SsId = &v
}

// GetBssId returns the BssId field value if set, zero value otherwise.
func (o *EventNotification) GetBssId() string {
	if o == nil || o.BssId == nil {
		var ret string
		return ret
	}
	return *o.BssId
}

// GetBssIdOk returns a tuple with the BssId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetBssIdOk() (*string, bool) {
	if o == nil || o.BssId == nil {
		return nil, false
	}
	return o.BssId, true
}

// HasBssId returns a boolean if a field has been set.
func (o *EventNotification) HasBssId() bool {
	if o != nil && o.BssId != nil {
		return true
	}

	return false
}

// SetBssId gets a reference to the given string and assigns it to the BssId field.
func (o *EventNotification) SetBssId(v string) {
	o.BssId = &v
}

// GetStartWlan returns the StartWlan field value if set, zero value otherwise.
func (o *EventNotification) GetStartWlan() time.Time {
	if o == nil || o.StartWlan == nil {
		var ret time.Time
		return ret
	}
	return *o.StartWlan
}

// GetStartWlanOk returns a tuple with the StartWlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetStartWlanOk() (*time.Time, bool) {
	if o == nil || o.StartWlan == nil {
		return nil, false
	}
	return o.StartWlan, true
}

// HasStartWlan returns a boolean if a field has been set.
func (o *EventNotification) HasStartWlan() bool {
	if o != nil && o.StartWlan != nil {
		return true
	}

	return false
}

// SetStartWlan gets a reference to the given time.Time and assigns it to the StartWlan field.
func (o *EventNotification) SetStartWlan(v time.Time) {
	o.StartWlan = &v
}

// GetEndWlan returns the EndWlan field value if set, zero value otherwise.
func (o *EventNotification) GetEndWlan() time.Time {
	if o == nil || o.EndWlan == nil {
		var ret time.Time
		return ret
	}
	return *o.EndWlan
}

// GetEndWlanOk returns a tuple with the EndWlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetEndWlanOk() (*time.Time, bool) {
	if o == nil || o.EndWlan == nil {
		return nil, false
	}
	return o.EndWlan, true
}

// HasEndWlan returns a boolean if a field has been set.
func (o *EventNotification) HasEndWlan() bool {
	if o != nil && o.EndWlan != nil {
		return true
	}

	return false
}

// SetEndWlan gets a reference to the given time.Time and assigns it to the EndWlan field.
func (o *EventNotification) SetEndWlan(v time.Time) {
	o.EndWlan = &v
}

// GetPduSessInfos returns the PduSessInfos field value if set, zero value otherwise.
func (o *EventNotification) GetPduSessInfos() []PduSessionInformation {
	if o == nil || o.PduSessInfos == nil {
		var ret []PduSessionInformation
		return ret
	}
	return o.PduSessInfos
}

// GetPduSessInfosOk returns a tuple with the PduSessInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetPduSessInfosOk() ([]PduSessionInformation, bool) {
	if o == nil || o.PduSessInfos == nil {
		return nil, false
	}
	return o.PduSessInfos, true
}

// HasPduSessInfos returns a boolean if a field has been set.
func (o *EventNotification) HasPduSessInfos() bool {
	if o != nil && o.PduSessInfos != nil {
		return true
	}

	return false
}

// SetPduSessInfos gets a reference to the given []PduSessionInformation and assigns it to the PduSessInfos field.
func (o *EventNotification) SetPduSessInfos(v []PduSessionInformation) {
	o.PduSessInfos = v
}

// GetUpfInfo returns the UpfInfo field value if set, zero value otherwise.
func (o *EventNotification) GetUpfInfo() UpfInformation {
	if o == nil || o.UpfInfo == nil {
		var ret UpfInformation
		return ret
	}
	return *o.UpfInfo
}

// GetUpfInfoOk returns a tuple with the UpfInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventNotification) GetUpfInfoOk() (*UpfInformation, bool) {
	if o == nil || o.UpfInfo == nil {
		return nil, false
	}
	return o.UpfInfo, true
}

// HasUpfInfo returns a boolean if a field has been set.
func (o *EventNotification) HasUpfInfo() bool {
	if o != nil && o.UpfInfo != nil {
		return true
	}

	return false
}

// SetUpfInfo gets a reference to the given UpfInformation and assigns it to the UpfInfo field.
func (o *EventNotification) SetUpfInfo(v UpfInformation) {
	o.UpfInfo = &v
}

func (o EventNotification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["event"] = o.Event
	}
	if true {
		toSerialize["timeStamp"] = o.TimeStamp.Unix() // added timestamp as int64 (preferred)
	}
	if o.Supi != nil {
		toSerialize["supi"] = o.Supi
	}
	if o.Gpsi != nil {
		toSerialize["gpsi"] = o.Gpsi
	}
	if o.UeIpAddr != nil {
		toSerialize["ueIpAddr"] = o.UeIpAddr
	}
	if o.TransacInfos != nil {
		toSerialize["transacInfos"] = o.TransacInfos
	}
	if o.SourceDnai != nil {
		toSerialize["sourceDnai"] = o.SourceDnai
	}
	if o.TargetDnai != nil {
		toSerialize["targetDnai"] = o.TargetDnai
	}
	if o.DnaiChgType != nil {
		toSerialize["dnaiChgType"] = o.DnaiChgType
	}
	if o.SourceUeIpv4Addr != nil {
		toSerialize["sourceUeIpv4Addr"] = o.SourceUeIpv4Addr
	}
	if o.SourceUeIpv6Prefix != nil {
		toSerialize["sourceUeIpv6Prefix"] = o.SourceUeIpv6Prefix
	}
	if o.TargetUeIpv4Addr != nil {
		toSerialize["targetUeIpv4Addr"] = o.TargetUeIpv4Addr
	}
	if o.TargetUeIpv6Prefix != nil {
		toSerialize["targetUeIpv6Prefix"] = o.TargetUeIpv6Prefix
	}
	if o.SourceTraRouting.IsSet() {
		toSerialize["sourceTraRouting"] = o.SourceTraRouting.Get()
	}
	if o.TargetTraRouting.IsSet() {
		toSerialize["targetTraRouting"] = o.TargetTraRouting.Get()
	}
	if o.UeMac != nil {
		toSerialize["ueMac"] = o.UeMac
	}
	if o.AdIpv4Addr != nil {
		toSerialize["adIpv4Addr"] = o.AdIpv4Addr
	}
	if o.AdIpv6Prefix != nil {
		toSerialize["adIpv6Prefix"] = o.AdIpv6Prefix
	}
	if o.ReIpv4Addr != nil {
		toSerialize["reIpv4Addr"] = o.ReIpv4Addr
	}
	if o.ReIpv6Prefix != nil {
		toSerialize["reIpv6Prefix"] = o.ReIpv6Prefix
	}
	if o.PlmnId != nil {
		toSerialize["plmnId"] = o.PlmnId
	}
	if o.AccType != nil {
		toSerialize["accType"] = o.AccType
	}
	if o.PduSeId != nil {
		toSerialize["pduSeId"] = o.PduSeId
	}
	if o.RatType != nil {
		toSerialize["ratType"] = o.RatType
	}
	if o.DddStatus != nil {
		toSerialize["dddStatus"] = o.DddStatus
	}
	if o.DddTraDescriptor != nil {
		toSerialize["dddTraDescriptor"] = o.DddTraDescriptor
	}
	if o.MaxWaitTime != nil {
		toSerialize["maxWaitTime"] = o.MaxWaitTime
	}
	if o.CommFailure != nil {
		toSerialize["commFailure"] = o.CommFailure
	}
	if o.Ipv4Addr != nil {
		toSerialize["ipv4Addr"] = o.Ipv4Addr
	}
	if o.Ipv6Prefixes != nil {
		toSerialize["ipv6Prefixes"] = o.Ipv6Prefixes
	}
	if o.Ipv6Addrs != nil {
		toSerialize["ipv6Addrs"] = o.Ipv6Addrs
	}
	if o.PduSessType != nil {
		toSerialize["pduSessType"] = o.PduSessType
	}
	if o.Qfi != nil {
		toSerialize["qfi"] = o.Qfi
	}
	if o.AppId != nil {
		toSerialize["appId"] = o.AppId
	}
	if o.EthfDescs != nil {
		toSerialize["ethfDescs"] = o.EthfDescs
	}
	if o.FDescs != nil {
		toSerialize["fDescs"] = o.FDescs
	}
	if o.Dnn != nil {
		toSerialize["dnn"] = o.Dnn
	}
	if o.Snssai != nil {
		toSerialize["snssai"] = o.Snssai
	}
	if o.UlDelays != nil {
		toSerialize["ulDelays"] = o.UlDelays
	}
	if o.DlDelays != nil {
		toSerialize["dlDelays"] = o.DlDelays
	}
	if o.RtDelays != nil {
		toSerialize["rtDelays"] = o.RtDelays
	}
	if o.TimeWindow != nil {
		toSerialize["timeWindow"] = o.TimeWindow
	}
	if o.SmNasFromUe != nil {
		toSerialize["smNasFromUe"] = o.SmNasFromUe
	}
	if o.SmNasFromSmf != nil {
		toSerialize["smNasFromSmf"] = o.SmNasFromSmf
	}
	if o.UpRedTrans != nil {
		toSerialize["upRedTrans"] = o.UpRedTrans
	}
	if o.SsId != nil {
		toSerialize["ssId"] = o.SsId
	}
	if o.BssId != nil {
		toSerialize["bssId"] = o.BssId
	}
	if o.StartWlan != nil {
		toSerialize["startWlan"] = o.StartWlan
	}
	if o.EndWlan != nil {
		toSerialize["endWlan"] = o.EndWlan
	}
	if o.PduSessInfos != nil {
		toSerialize["pduSessInfos"] = o.PduSessInfos
	}
	if o.UpfInfo != nil {
		toSerialize["upfInfo"] = o.UpfInfo
	}
	return json.Marshal(toSerialize)
}

type NullableEventNotification struct {
	value *EventNotification
	isSet bool
}

func (v NullableEventNotification) Get() *EventNotification {
	return v.value
}

func (v *NullableEventNotification) Set(val *EventNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableEventNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableEventNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventNotification(val *EventNotification) *NullableEventNotification {
	return &NullableEventNotification{value: val, isSet: true}
}

func (v NullableEventNotification) MarshalJSON() ([]byte, error) {
	// custom marshaling for timestamp: time.Time => int64 (preferred)
	type EventNotificationAlias EventNotification
	return json.Marshal(&struct {
		TimeStamp int64 `json:"timeStamp"`
		*EventNotificationAlias
	}{
		EventNotificationAlias: (*EventNotificationAlias)(v.value),
		TimeStamp: v.value.TimeStamp.Unix(),
	})
}

func (v *NullableEventNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	// custom unmarshaling for timestamp: string (as used in SMF) => time.Time
	type EventNotificationAlias EventNotification
	alias := &struct {
		TimeStamp string `json:"timeStamp"`
		*EventNotificationAlias
	}{
		EventNotificationAlias: (*EventNotificationAlias)(v.value),
	}
    err := json.Unmarshal(src, alias)
    if err != nil { return err; }
	timeStampInt, err := strconv.Atoi(alias.TimeStamp)
    if err != nil { return err; }
	v.value.TimeStamp = time.Unix(int64(timeStampInt), 0)
	return nil
}

// Unmarshaling of the Report with timestamp. This method is called by json.Unmarshal
func (v *EventNotification) UnmarshalJSON(src []byte) error {
	// custom unmarshaling for timestamp: string (as used in SMF) => time.Time
	type EventNotificationAlias EventNotification
	alias := &struct {
		TimeStamp string `json:"timeStamp"`
		*EventNotificationAlias
	}{
		EventNotificationAlias: (*EventNotificationAlias)(v),
	}
    err := json.Unmarshal(src, alias)
    if err != nil { return err; }
	timeStampInt, err := strconv.Atoi(alias.TimeStamp)
    if err != nil { return err; }
	v.TimeStamp = time.Unix(int64(timeStampInt), 0)
	return nil
}
