
apiVersion: v2
name: ueransim
description: A Helm chart to deploy UERANSIM
version: 2.0.17
appVersion: latest
icon: https://raw.githubusercontent.com/aligungr/UERANSIM/master/.github/logo.png
maintainers:
  - email: abderaouf.khichane@orange.com
    name: Abderaouf KHICHANE
