/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

import (
	"context"
	"errors"
	"net/http"
)

// IndividualNWDAFEventSubscriptionTransferDocumentApiService is a service that implements the logic for the IndividualNWDAFEventSubscriptionTransferDocumentApiServicer
// This service should implement the business logic for every endpoint for the IndividualNWDAFEventSubscriptionTransferDocumentApi API.
// Include any external packages or services that will be required by this service.
type IndividualNWDAFEventSubscriptionTransferDocumentApiService struct {
}

// NewIndividualNWDAFEventSubscriptionTransferDocumentApiService creates a default api service
func NewIndividualNWDAFEventSubscriptionTransferDocumentApiService() IndividualNWDAFEventSubscriptionTransferDocumentApiServicer {
	return &IndividualNWDAFEventSubscriptionTransferDocumentApiService{}
}

// DeleteNWDAFEventSubscriptionTransfer - Delete an existing Individual NWDAF Event Subscription Transfer
func (s *IndividualNWDAFEventSubscriptionTransferDocumentApiService) DeleteNWDAFEventSubscriptionTransfer(ctx context.Context, transferId string) (ImplResponse, error) {
	// TODO - update DeleteNWDAFEventSubscriptionTransfer with the required logic for this service method.
	// Add api_individual_nwdaf_event_subscription_transfer_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(307, RedirectResponse{}) or use other options such as http.Ok ...
	//return Response(307, RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response Response(308, RedirectResponse{}) or use other options such as http.Ok ...
	//return Response(308, RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(400, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(401, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(403, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(404, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(429, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(500, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(501, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(501, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(503, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteNWDAFEventSubscriptionTransfer method not implemented")
}

// UpdateNWDAFEventSubscriptionTransfer - Update an existing Individual NWDAF Event Subscription Transfer
func (s *IndividualNWDAFEventSubscriptionTransferDocumentApiService) UpdateNWDAFEventSubscriptionTransfer(ctx context.Context, transferId string, analyticsSubscriptionsTransfer AnalyticsSubscriptionsTransfer) (ImplResponse, error) {
	// TODO - update UpdateNWDAFEventSubscriptionTransfer with the required logic for this service method.
	// Add api_individual_nwdaf_event_subscription_transfer_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(307, RedirectResponse{}) or use other options such as http.Ok ...
	//return Response(307, RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response Response(308, RedirectResponse{}) or use other options such as http.Ok ...
	//return Response(308, RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(400, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(401, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(401, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(403, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(403, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(404, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(404, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(411, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(411, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(413, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(413, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(415, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(415, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(429, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(429, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(500, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(500, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(501, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(501, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(503, ProblemDetails{}) or use other options such as http.Ok ...
	//return Response(503, ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response Response(0, {}) or use other options such as http.Ok ...
	//return Response(0, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateNWDAFEventSubscriptionTransfer method not implemented")
}
