/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

import (
	"time"
)

// RedundantTransmissionExpPerTs1 - The redundant transmission experience per Time Slot.
type RedundantTransmissionExpPerTs1 struct {

	// string with format 'date-time' as defined in OpenAPI.
	TsStart time.Time `json:"tsStart"`

	// indicating a time in seconds.
	TsDuration int32 `json:"tsDuration"`

	RedTransExp string `json:"redTransExp"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	UeRatio int32 `json:"ueRatio,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Confidence int32 `json:"confidence,omitempty"`
}

// AssertRedundantTransmissionExpPerTs1Required checks if the required fields are not zero-ed
func AssertRedundantTransmissionExpPerTs1Required(obj RedundantTransmissionExpPerTs1) error {
	elements := map[string]interface{}{
		"tsStart":     obj.TsStart,
		"tsDuration":  obj.TsDuration,
		"redTransExp": obj.RedTransExp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseRedundantTransmissionExpPerTs1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RedundantTransmissionExpPerTs1 (e.g. [][]RedundantTransmissionExpPerTs1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRedundantTransmissionExpPerTs1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRedundantTransmissionExpPerTs1, ok := obj.(RedundantTransmissionExpPerTs1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRedundantTransmissionExpPerTs1Required(aRedundantTransmissionExpPerTs1)
	})
}
