/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// NsiLoadLevelInfo - Represents the network slice and optionally the associated network slice instance and the load level information.
type NsiLoadLevelInfo struct {

	// Load level information of the network slice and the optionally associated network slice instance.
	LoadLevelInformation int32 `json:"loadLevelInformation"`

	Snssai Snssai `json:"snssai"`

	// Contains the Identifier of the selected Network Slice instance
	NsiId string `json:"nsiId,omitempty"`

	ResUsage ResourceUsage `json:"resUsage,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NumOfExceedLoadLevelThr int32 `json:"numOfExceedLoadLevelThr,omitempty"`

	ExceedLoadLevelThrInd bool `json:"exceedLoadLevelThrInd,omitempty"`

	NetworkArea NetworkAreaInfo `json:"networkArea,omitempty"`

	TimePeriod TimeWindow `json:"timePeriod,omitempty"`

	NumOfUes NumberAverage `json:"numOfUes,omitempty"`

	NumOfPduSess NumberAverage `json:"numOfPduSess,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Confidence int32 `json:"confidence,omitempty"`
}

// AssertNsiLoadLevelInfoRequired checks if the required fields are not zero-ed
func AssertNsiLoadLevelInfoRequired(obj NsiLoadLevelInfo) error {
	elements := map[string]interface{}{
		"loadLevelInformation": obj.LoadLevelInformation,
		"snssai":               obj.Snssai,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSnssaiRequired(obj.Snssai); err != nil {
		return err
	}
	if err := AssertResourceUsageRequired(obj.ResUsage); err != nil {
		return err
	}
	if err := AssertNetworkAreaInfoRequired(obj.NetworkArea); err != nil {
		return err
	}
	if err := AssertTimeWindowRequired(obj.TimePeriod); err != nil {
		return err
	}
	if err := AssertNumberAverageRequired(obj.NumOfUes); err != nil {
		return err
	}
	if err := AssertNumberAverageRequired(obj.NumOfPduSess); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNsiLoadLevelInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NsiLoadLevelInfo (e.g. [][]NsiLoadLevelInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNsiLoadLevelInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNsiLoadLevelInfo, ok := obj.(NsiLoadLevelInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNsiLoadLevelInfoRequired(aNsiLoadLevelInfo)
	})
}
