/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// TopApplication - Top application that contributes the most to the traffic.
type TopApplication struct {

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	IpTrafficFilter FlowInfo `json:"ipTrafficFilter,omitempty"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	Ratio int32 `json:"ratio,omitempty"`
}

// AssertTopApplicationRequired checks if the required fields are not zero-ed
func AssertTopApplicationRequired(obj TopApplication) error {
	if err := AssertFlowInfoRequired(obj.IpTrafficFilter); err != nil {
		return err
	}
	return nil
}

// AssertRecurseTopApplicationRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TopApplication (e.g. [][]TopApplication), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTopApplicationRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTopApplication, ok := obj.(TopApplication)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTopApplicationRequired(aTopApplication)
	})
}
