/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// SupportedGadShapes - Indicates supported GAD shapes.
type SupportedGadShapes struct {
}

// AssertSupportedGadShapesRequired checks if the required fields are not zero-ed
func AssertSupportedGadShapesRequired(obj SupportedGadShapes) error {
	return nil
}

// AssertRecurseSupportedGadShapesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SupportedGadShapes (e.g. [][]SupportedGadShapes), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSupportedGadShapesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSupportedGadShapes, ok := obj.(SupportedGadShapes)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSupportedGadShapesRequired(aSupportedGadShapes)
	})
}
