/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// NetworkPerfRequirement1 - Represents a network performance requirement.
type NetworkPerfRequirement1 struct {
	NwPerfType NetworkPerfType `json:"nwPerfType"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	RelativeRatio int32 `json:"relativeRatio,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AbsoluteNum int32 `json:"absoluteNum,omitempty"`
}

// AssertNetworkPerfRequirement1Required checks if the required fields are not zero-ed
func AssertNetworkPerfRequirement1Required(obj NetworkPerfRequirement1) error {
	elements := map[string]interface{}{
		"nwPerfType": obj.NwPerfType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkPerfTypeRequired(obj.NwPerfType); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNetworkPerfRequirement1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NetworkPerfRequirement1 (e.g. [][]NetworkPerfRequirement1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNetworkPerfRequirement1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNetworkPerfRequirement1, ok := obj.(NetworkPerfRequirement1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNetworkPerfRequirement1Required(aNetworkPerfRequirement1)
	})
}
