/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// NotificationMethod - Possible values are - PERIODIC: The subscribe of NWDAF Event is periodically. The periodic of the notification is identified by repetitionPeriod defined in subclause 5.1.6.2.3. - THRESHOLD: The subscribe of NWDAF Event is upon threshold exceeded.
type NotificationMethod string

// List of NotificationMethodAnyOf
const (
	NOTIFICATIONMETHOD_PERIODIC  NotificationMethod = "PERIODIC"
	NOTIFICATIONMETHOD_THRESHOLD NotificationMethod = "THRESHOLD"
)

// AssertNotificationMethodRequired checks if the required fields are not zero-ed
func AssertNotificationMethodRequired(obj NotificationMethod) error {
	return nil
}

// AssertRecurseNotificationMethodRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotificationMethod (e.g. [][]NotificationMethod), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotificationMethodRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotificationMethod, ok := obj.(NotificationMethod)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotificationMethodRequired(aNotificationMethod)
	})
}
