/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// ModelInfo - Contains information about an ML model.
type ModelInfo struct {
	AnalyticsId NwdafEvent `json:"analyticsId"`

	// String providing an URI formatted according to RFC 3986
	MlFileAddr string `json:"mlFileAddr"`
}

// AssertModelInfoRequired checks if the required fields are not zero-ed
func AssertModelInfoRequired(obj ModelInfo) error {
	elements := map[string]interface{}{
		"analyticsId": obj.AnalyticsId,
		"mlFileAddr":  obj.MlFileAddr,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNwdafEventRequired(obj.AnalyticsId); err != nil {
		return err
	}
	return nil
}

// AssertRecurseModelInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ModelInfo (e.g. [][]ModelInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModelInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModelInfo, ok := obj.(ModelInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModelInfoRequired(aModelInfo)
	})
}
