/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// DispersionRequirement1 - Represents the dispersion analytics requirements.
type DispersionRequirement1 struct {
	DisperType DispersionType `json:"disperType"`

	ClassCriters []ClassCriterion1 `json:"classCriters,omitempty"`

	RankCriters []RankingCriterion1 `json:"rankCriters,omitempty"`

	DispOrderCriter DispersionOrderingCriterion `json:"dispOrderCriter,omitempty"`

	Order MatchingDirection `json:"order,omitempty"`
}

// AssertDispersionRequirement1Required checks if the required fields are not zero-ed
func AssertDispersionRequirement1Required(obj DispersionRequirement1) error {
	elements := map[string]interface{}{
		"disperType": obj.DisperType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDispersionTypeRequired(obj.DisperType); err != nil {
		return err
	}
	for _, el := range obj.ClassCriters {
		if err := AssertClassCriterion1Required(el); err != nil {
			return err
		}
	}
	for _, el := range obj.RankCriters {
		if err := AssertRankingCriterion1Required(el); err != nil {
			return err
		}
	}
	if err := AssertDispersionOrderingCriterionRequired(obj.DispOrderCriter); err != nil {
		return err
	}
	if err := AssertMatchingDirectionRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertRecurseDispersionRequirement1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DispersionRequirement1 (e.g. [][]DispersionRequirement1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDispersionRequirement1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDispersionRequirement1, ok := obj.(DispersionRequirement1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDispersionRequirement1Required(aDispersionRequirement1)
	})
}
