/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// WlanOrderingCriterion - Possible values are   - TIME_SLOT_START: Indicates the order of time slot start.   - NUMBER_OF_UES: Indicates the order of number of UEs.   - RSSI: Indicates the order of RSSI.   - RTT: Indicates the order of RTT.   - TRAFFIC_INFO: Indicates the order of Traffic information.
type WlanOrderingCriterion struct {
}

// AssertWlanOrderingCriterionRequired checks if the required fields are not zero-ed
func AssertWlanOrderingCriterionRequired(obj WlanOrderingCriterion) error {
	return nil
}

// AssertRecurseWlanOrderingCriterionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WlanOrderingCriterion (e.g. [][]WlanOrderingCriterion), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWlanOrderingCriterionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWlanOrderingCriterion, ok := obj.(WlanOrderingCriterion)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWlanOrderingCriterionRequired(aWlanOrderingCriterion)
	})
}
