/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// NetworkPerfRequirement - Represents a network performance requirement.
type NetworkPerfRequirement struct {
	NwPerfType NetworkPerfType `json:"nwPerfType"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.
	RelativeRatio int32 `json:"relativeRatio,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AbsoluteNum int32 `json:"absoluteNum,omitempty"`
}

// AssertNetworkPerfRequirementRequired checks if the required fields are not zero-ed
func AssertNetworkPerfRequirementRequired(obj NetworkPerfRequirement) error {
	elements := map[string]interface{}{
		"nwPerfType": obj.NwPerfType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetworkPerfTypeRequired(obj.NwPerfType); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNetworkPerfRequirementRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NetworkPerfRequirement (e.g. [][]NetworkPerfRequirement), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNetworkPerfRequirementRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNetworkPerfRequirement, ok := obj.(NetworkPerfRequirement)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNetworkPerfRequirementRequired(aNetworkPerfRequirement)
	})
}
