/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package events

// PointUncertaintyCircle - Ellipsoid point with uncertainty circle.
type PointUncertaintyCircle struct {
	GadShape

	Point GeographicalCoordinates `json:"point"`

	// Indicates value of uncertainty.
	Uncertainty float32 `json:"uncertainty"`
}

// AssertPointUncertaintyCircleRequired checks if the required fields are not zero-ed
func AssertPointUncertaintyCircleRequired(obj PointUncertaintyCircle) error {
	elements := map[string]interface{}{
		"point":       obj.Point,
		"uncertainty": obj.Uncertainty,
		"shape":       obj.Shape,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertGadShapeRequired(obj.GadShape); err != nil {
		return err
	}

	if err := AssertGeographicalCoordinatesRequired(obj.Point); err != nil {
		return err
	}
	return nil
}

// AssertRecursePointUncertaintyCircleRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PointUncertaintyCircle (e.g. [][]PointUncertaintyCircle), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePointUncertaintyCircleRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPointUncertaintyCircle, ok := obj.(PointUncertaintyCircle)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPointUncertaintyCircleRequired(aPointUncertaintyCircle)
	})
}
