/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

import (
	"context"
	"net/http"
)

// IndividualNWDAFMLModelProvisionSubscriptionDocumentApiRouter defines the required methods for binding the api requests to a responses for the IndividualNWDAFMLModelProvisionSubscriptionDocumentApi
// The IndividualNWDAFMLModelProvisionSubscriptionDocumentApiRouter implementation should parse necessary information from the http request,
// pass the data to a IndividualNWDAFMLModelProvisionSubscriptionDocumentApiServicer to perform the required actions, then write the service results to the http response.
type IndividualNWDAFMLModelProvisionSubscriptionDocumentApiRouter interface {
	DeleteNWDAFMLModelProvisionSubcription(http.ResponseWriter, *http.Request)
	UpdateNWDAFMLModelProvisionSubcription(http.ResponseWriter, *http.Request)
}

// SubscriptionsCollectionApiRouter defines the required methods for binding the api requests to a responses for the SubscriptionsCollectionApi
// The SubscriptionsCollectionApiRouter implementation should parse necessary information from the http request,
// pass the data to a SubscriptionsCollectionApiServicer to perform the required actions, then write the service results to the http response.
type SubscriptionsCollectionApiRouter interface {
	CreateNWDAFMLModelProvisionSubcription(http.ResponseWriter, *http.Request)
}

// IndividualNWDAFMLModelProvisionSubscriptionDocumentApiServicer defines the api actions for the IndividualNWDAFMLModelProvisionSubscriptionDocumentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type IndividualNWDAFMLModelProvisionSubscriptionDocumentApiServicer interface {
	DeleteNWDAFMLModelProvisionSubcription(context.Context, string) (ImplResponse, error)
	UpdateNWDAFMLModelProvisionSubcription(context.Context, string, NwdafMlModelProvSubsc) (ImplResponse, error)
}

// SubscriptionsCollectionApiServicer defines the api actions for the SubscriptionsCollectionApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SubscriptionsCollectionApiServicer interface {
	CreateNWDAFMLModelProvisionSubcription(context.Context, NwdafMlModelProvSubsc) (ImplResponse, error)
}
