/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// RedundantTransmissionExpReq - Represents other redundant transmission experience analytics requirements.
type RedundantTransmissionExpReq struct {
	RedTOrderCriter RedTransExpOrderingCriterion `json:"redTOrderCriter,omitempty"`

	Order MatchingDirection `json:"order,omitempty"`
}

// AssertRedundantTransmissionExpReqRequired checks if the required fields are not zero-ed
func AssertRedundantTransmissionExpReqRequired(obj RedundantTransmissionExpReq) error {
	if err := AssertRedTransExpOrderingCriterionRequired(obj.RedTOrderCriter); err != nil {
		return err
	}
	if err := AssertMatchingDirectionRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertRecurseRedundantTransmissionExpReqRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RedundantTransmissionExpReq (e.g. [][]RedundantTransmissionExpReq), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRedundantTransmissionExpReqRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRedundantTransmissionExpReq, ok := obj.(RedundantTransmissionExpReq)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRedundantTransmissionExpReqRequired(aRedundantTransmissionExpReq)
	})
}
