/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// Polygon - Polygon.
type Polygon struct {
	GadShape

	// List of points.
	PointList []GeographicalCoordinates `json:"pointList"`
}

// AssertPolygonRequired checks if the required fields are not zero-ed
func AssertPolygonRequired(obj Polygon) error {
	elements := map[string]interface{}{
		"pointList": obj.PointList,
		"shape":     obj.Shape,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertGadShapeRequired(obj.GadShape); err != nil {
		return err
	}

	for _, el := range obj.PointList {
		if err := AssertGeographicalCoordinatesRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecursePolygonRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Polygon (e.g. [][]Polygon), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePolygonRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPolygon, ok := obj.(Polygon)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPolygonRequired(aPolygon)
	})
}
