/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type DispersionOrderingCriterionAnyOf string

// List of DispersionOrderingCriterionAnyOf
const (
	DISPERSIONORDERINGCRITERIONANYOF_TIME_SLOT_START    DispersionOrderingCriterionAnyOf = "TIME_SLOT_START"
	DISPERSIONORDERINGCRITERIONANYOF_DISPERSION         DispersionOrderingCriterionAnyOf = "DISPERSION"
	DISPERSIONORDERINGCRITERIONANYOF_CLASSIFICATION     DispersionOrderingCriterionAnyOf = "CLASSIFICATION"
	DISPERSIONORDERINGCRITERIONANYOF_RANKING            DispersionOrderingCriterionAnyOf = "RANKING"
	DISPERSIONORDERINGCRITERIONANYOF_PERCENTILE_RANKING DispersionOrderingCriterionAnyOf = "PERCENTILE_RANKING"
)

// AssertDispersionOrderingCriterionAnyOfRequired checks if the required fields are not zero-ed
func AssertDispersionOrderingCriterionAnyOfRequired(obj DispersionOrderingCriterionAnyOf) error {
	return nil
}

// AssertRecurseDispersionOrderingCriterionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DispersionOrderingCriterionAnyOf (e.g. [][]DispersionOrderingCriterionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDispersionOrderingCriterionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDispersionOrderingCriterionAnyOf, ok := obj.(DispersionOrderingCriterionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDispersionOrderingCriterionAnyOfRequired(aDispersionOrderingCriterionAnyOf)
	})
}
