/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// FailureCode - Possible values are - UNAVAILABLE_ML_MODEL: Indicates the requested ML model for the event is unavailable.
type FailureCode struct {
}

// AssertFailureCodeRequired checks if the required fields are not zero-ed
func AssertFailureCodeRequired(obj FailureCode) error {
	return nil
}

// AssertRecurseFailureCodeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FailureCode (e.g. [][]FailureCode), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFailureCodeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFailureCode, ok := obj.(FailureCode)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFailureCodeRequired(aFailureCode)
	})
}
