/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// DnPerformanceReq - Represents other DN performance analytics requirements.
type DnPerformanceReq struct {
	DnPerfOrderCriter DnPerfOrderingCriterion `json:"dnPerfOrderCriter,omitempty"`

	Order MatchingDirection `json:"order,omitempty"`

	ReportThresholds []ThresholdLevel `json:"reportThresholds,omitempty"`
}

// AssertDnPerformanceReqRequired checks if the required fields are not zero-ed
func AssertDnPerformanceReqRequired(obj DnPerformanceReq) error {
	if err := AssertDnPerfOrderingCriterionRequired(obj.DnPerfOrderCriter); err != nil {
		return err
	}
	if err := AssertMatchingDirectionRequired(obj.Order); err != nil {
		return err
	}
	for _, el := range obj.ReportThresholds {
		if err := AssertThresholdLevelRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseDnPerformanceReqRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DnPerformanceReq (e.g. [][]DnPerformanceReq), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDnPerformanceReqRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDnPerformanceReq, ok := obj.(DnPerformanceReq)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDnPerformanceReqRequired(aDnPerformanceReq)
	})
}
