/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type PointUncertaintyCircleAllOf struct {
	Point GeographicalCoordinates `json:"point"`

	// Indicates value of uncertainty.
	Uncertainty float32 `json:"uncertainty"`
}

// AssertPointUncertaintyCircleAllOfRequired checks if the required fields are not zero-ed
func AssertPointUncertaintyCircleAllOfRequired(obj PointUncertaintyCircleAllOf) error {
	elements := map[string]interface{}{
		"point":       obj.Point,
		"uncertainty": obj.Uncertainty,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertGeographicalCoordinatesRequired(obj.Point); err != nil {
		return err
	}
	return nil
}

// AssertRecursePointUncertaintyCircleAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PointUncertaintyCircleAllOf (e.g. [][]PointUncertaintyCircleAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePointUncertaintyCircleAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPointUncertaintyCircleAllOf, ok := obj.(PointUncertaintyCircleAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPointUncertaintyCircleAllOfRequired(aPointUncertaintyCircleAllOf)
	})
}
