/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

type ExpectedAnalyticsTypeAnyOf string

// List of ExpectedAnalyticsTypeAnyOf
const (
	EXPECTEDANALYTICSTYPEANYOF_MOBILITY            ExpectedAnalyticsTypeAnyOf = "MOBILITY"
	EXPECTEDANALYTICSTYPEANYOF_COMMUN              ExpectedAnalyticsTypeAnyOf = "COMMUN"
	EXPECTEDANALYTICSTYPEANYOF_MOBILITY_AND_COMMUN ExpectedAnalyticsTypeAnyOf = "MOBILITY_AND_COMMUN"
)

// AssertExpectedAnalyticsTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertExpectedAnalyticsTypeAnyOfRequired(obj ExpectedAnalyticsTypeAnyOf) error {
	return nil
}

// AssertRecurseExpectedAnalyticsTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ExpectedAnalyticsTypeAnyOf (e.g. [][]ExpectedAnalyticsTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseExpectedAnalyticsTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aExpectedAnalyticsTypeAnyOf, ok := obj.(ExpectedAnalyticsTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertExpectedAnalyticsTypeAnyOfRequired(aExpectedAnalyticsTypeAnyOf)
	})
}
