/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

import (
	"time"
)

// MlEventSubscription - Represents a subscription to a single event.
type MlEventSubscription struct {
	MLEvent NwdafEvent `json:"mLEvent"`

	MLEventFilter EventFilter `json:"mLEventFilter"`

	TgtUe TargetUeInformation `json:"tgtUe,omitempty"`

	MLTargetPeriod TimeWindow `json:"mLTargetPeriod,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ExpiryTime time.Time `json:"expiryTime,omitempty"`
}

// AssertMlEventSubscriptionRequired checks if the required fields are not zero-ed
func AssertMlEventSubscriptionRequired(obj MlEventSubscription) error {
	elements := map[string]interface{}{
		"mLEvent":       obj.MLEvent,
		"mLEventFilter": obj.MLEventFilter,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNwdafEventRequired(obj.MLEvent); err != nil {
		return err
	}
	if err := AssertEventFilterRequired(obj.MLEventFilter); err != nil {
		return err
	}
	if err := AssertTargetUeInformationRequired(obj.TgtUe); err != nil {
		return err
	}
	if err := AssertTimeWindowRequired(obj.MLTargetPeriod); err != nil {
		return err
	}
	return nil
}

// AssertRecurseMlEventSubscriptionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MlEventSubscription (e.g. [][]MlEventSubscription), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMlEventSubscriptionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMlEventSubscription, ok := obj.(MlEventSubscription)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMlEventSubscriptionRequired(aMlEventSubscription)
	})
}
