/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nbiml

// GeographicalCoordinates - Geographical coordinates.
type GeographicalCoordinates struct {
	Lon float64 `json:"lon"`

	Lat float64 `json:"lat"`
}

// AssertGeographicalCoordinatesRequired checks if the required fields are not zero-ed
func AssertGeographicalCoordinatesRequired(obj GeographicalCoordinates) error {
	elements := map[string]interface{}{
		"lon": obj.Lon,
		"lat": obj.Lat,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGeographicalCoordinatesRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GeographicalCoordinates (e.g. [][]GeographicalCoordinates), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGeographicalCoordinatesRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGeographicalCoordinates, ok := obj.(GeographicalCoordinates)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGeographicalCoordinatesRequired(aGeographicalCoordinates)
	})
}
