/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// ApplicationVolume - Application data volume per Application Id.
type ApplicationVolume struct {

	// String providing an application identifier.
	AppId string `json:"appId"`

	// Unsigned integer identifying a volume in units of bytes.
	AppVolume int64 `json:"appVolume"`
}

// AssertApplicationVolumeRequired checks if the required fields are not zero-ed
func AssertApplicationVolumeRequired(obj ApplicationVolume) error {
	elements := map[string]interface{}{
		"appId":     obj.AppId,
		"appVolume": obj.AppVolume,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseApplicationVolumeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApplicationVolume (e.g. [][]ApplicationVolume), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApplicationVolumeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApplicationVolume, ok := obj.(ApplicationVolume)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApplicationVolumeRequired(aApplicationVolume)
	})
}
