/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// DnPerfOrderingCriterion - Possible values are:     - AVERAGE_TRAFFIC_RATE: Indicates the average traffic rate.     - MAXIMUM_TRAFFIC_RATE: Indicates the maximum traffic rate.     - AVERAGE_PACKET_DELAY: Indicates the average packet delay.     - MAXIMUM_PACKET_DELAY: Indicates the maximum packet delay.     - AVERAGE_PACKET_LOSS_RATE: Indicates the average packet loss rate.
type DnPerfOrderingCriterion struct {
}

// AssertDnPerfOrderingCriterionRequired checks if the required fields are not zero-ed
func AssertDnPerfOrderingCriterionRequired(obj DnPerfOrderingCriterion) error {
	return nil
}

// AssertRecurseDnPerfOrderingCriterionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DnPerfOrderingCriterion (e.g. [][]DnPerfOrderingCriterion), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDnPerfOrderingCriterionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDnPerfOrderingCriterion, ok := obj.(DnPerfOrderingCriterion)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDnPerfOrderingCriterionRequired(aDnPerfOrderingCriterion)
	})
}
