/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

// ResourceUsage - The current usage of the virtual resources assigned to the NF instances belonging to a particular network slice instance.
type ResourceUsage struct {

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	CpuUsage int32 `json:"cpuUsage,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MemoryUsage int32 `json:"memoryUsage,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	StorageUsage int32 `json:"storageUsage,omitempty"`
}

// AssertResourceUsageRequired checks if the required fields are not zero-ed
func AssertResourceUsageRequired(obj ResourceUsage) error {
	return nil
}

// AssertRecurseResourceUsageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResourceUsage (e.g. [][]ResourceUsage), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseResourceUsageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResourceUsage, ok := obj.(ResourceUsage)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertResourceUsageRequired(aResourceUsage)
	})
}
