/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

type ContextTypeAnyOf string

// List of ContextTypeAnyOf
const (
	CONTEXTTYPEANYOF_PENDING_ANALYTICS    ContextTypeAnyOf = "PENDING_ANALYTICS"
	CONTEXTTYPEANYOF_HISTORICAL_ANALYTICS ContextTypeAnyOf = "HISTORICAL_ANALYTICS"
	CONTEXTTYPEANYOF_AGGR_SUBS            ContextTypeAnyOf = "AGGR_SUBS"
	CONTEXTTYPEANYOF_DATA                 ContextTypeAnyOf = "DATA"
	CONTEXTTYPEANYOF_AGGR_INFO            ContextTypeAnyOf = "AGGR_INFO"
	CONTEXTTYPEANYOF_ML_MODELS            ContextTypeAnyOf = "ML_MODELS"
)

// AssertContextTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertContextTypeAnyOfRequired(obj ContextTypeAnyOf) error {
	return nil
}

// AssertRecurseContextTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ContextTypeAnyOf (e.g. [][]ContextTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseContextTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aContextTypeAnyOf, ok := obj.(ContextTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertContextTypeAnyOfRequired(aContextTypeAnyOf)
	})
}
