/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

type WlanOrderingCriterionAnyOf string

// List of WlanOrderingCriterionAnyOf
const (
	WLANORDERINGCRITERIONANYOF_TIME_SLOT_START WlanOrderingCriterionAnyOf = "TIME_SLOT_START"
	WLANORDERINGCRITERIONANYOF_NUMBER_OF_UES   WlanOrderingCriterionAnyOf = "NUMBER_OF_UES"
	WLANORDERINGCRITERIONANYOF_RSSI            WlanOrderingCriterionAnyOf = "RSSI"
	WLANORDERINGCRITERIONANYOF_RTT             WlanOrderingCriterionAnyOf = "RTT"
	WLANORDERINGCRITERIONANYOF_TRAFFIC_INFO    WlanOrderingCriterionAnyOf = "TRAFFIC_INFO"
)

// AssertWlanOrderingCriterionAnyOfRequired checks if the required fields are not zero-ed
func AssertWlanOrderingCriterionAnyOfRequired(obj WlanOrderingCriterionAnyOf) error {
	return nil
}

// AssertRecurseWlanOrderingCriterionAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of WlanOrderingCriterionAnyOf (e.g. [][]WlanOrderingCriterionAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseWlanOrderingCriterionAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aWlanOrderingCriterionAnyOf, ok := obj.(WlanOrderingCriterionAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertWlanOrderingCriterionAnyOfRequired(aWlanOrderingCriterionAnyOf)
	})
}
