/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package analytics

type ServiceExperienceTypeAnyOf string

// List of ServiceExperienceTypeAnyOf
const (
	SERVICEEXPERIENCETYPEANYOF_VOICE ServiceExperienceTypeAnyOf = "VOICE"
	SERVICEEXPERIENCETYPEANYOF_VIDEO ServiceExperienceTypeAnyOf = "VIDEO"
)

// AssertServiceExperienceTypeAnyOfRequired checks if the required fields are not zero-ed
func AssertServiceExperienceTypeAnyOfRequired(obj ServiceExperienceTypeAnyOf) error {
	return nil
}

// AssertRecurseServiceExperienceTypeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServiceExperienceTypeAnyOf (e.g. [][]ServiceExperienceTypeAnyOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServiceExperienceTypeAnyOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServiceExperienceTypeAnyOf, ok := obj.(ServiceExperienceTypeAnyOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServiceExperienceTypeAnyOfRequired(aServiceExperienceTypeAnyOf)
	})
}
